const characterGoals = [
  'achieve moral perfection',
  'achieve spiritual enlightenment',
  'acquire riches',
  'advance a settlement',
  'advance religion',
  'advance status',
  'avenge a wrong',
  'avoid ridicule',
  'be a hero',
  'be left alone',
  'be loved by all',
  'be the best',
  'become an overseer',
  'bring balance',
  'bring forth justice',
  'bring law and order',
  'bring order to chaos',
  'build a better life',
  'build a relationship',
  'change the system',
  'collect a debt',
  'collect unique art',
  'create an item',
  'cure an ill',
  'cure disease',
  'deepen mystic power',
  'defeat a foe',
  'defeat romantic rival',
  'defend a place',
  'destroy an item',
  'discover the truth of their past',
  'enrich themselves',
  'escape from something',
  'explore and discover',
  'feed an addiction',
  'feel personal accomplishment',
  'fight the good fight',
  'find a home',
  'find a person',
  'find a soulmate',
  'find redemption',
  'find safe place to live',
  'find settlement resources',
  'find unique artifacts',
  'fulfill a duty',
  'gain fame and glory',
  'gain followers',
  'gain knowledge',
  'gain power and influence',
  'get revenge',
  'harm a rival',
  'have food to eat',
  'hedonism',
  'help the helpless',
  'learn of the old world',
  'leave their mark',
  'liberate those in bondage',
  'live in relative luxury',
  'make an agreement',
  'make contact with firstborn',
  'make many small impacts',
  'obtain an object',
  'oppress others',
  'pay a debt',
  'personal development',
  'protect a person',
  'protect a secret',
  'protect the innocent',
  'protect the status quo',
  'prove worthiness',
  'raise a family',
  'raise others from poverty',
  'rebel against power',
  'refute a falsehood',
  'rescue a person',
  'resolve a dispute',
  'restore a relationship',
  'scheme machinations',
  'secure provisions',
  'seek a truth',
  'seek forgiveness',
  'seek wisdom and knowledge',
  'seize power',
  'serve others',
  'serve the rightful ruler',
  'slay a creature',
  'solve ancient mystery',
  'spread faith',
  'stay true to friends and family',
  'survive the winter',
  'teach others',
  'travel to a place',
  'undermine a relationship',
  'unite settlements',
  'voice for the voiceless',
  'win affection',
];
