const storeGoods = {
  'cotton cloth': '5 sp',
  'bagpipes': '30 gp',
  'healer\'s kit': '5 gp',
  'chicken': '2 cp',
  'cinnamon': '2 gp',
  'pan flute': '12 gp',
  'basket': '4 sp',
  'gold': '50 gp',
  'sheep': '2 gp',
  'ale': '2 sp',
  'abacus': '2 gp',
  'component pouch': '25 gp',
  'cloves': '3 gp',
  'pig': '3 gp',
  'cook\'s utensils': '1 gp',
  'calligrapher\'s supplies': '10 gp',
  'thieves\'s tools': '25 gp',
  'crowbar': '2 gp',
  'silver or 1 sq. yd. of linen': '5 gp',
  'case': '1 gp',
  'wine common': '2 sp',
  'cobbler\'s tools': '5 gp',
  'cartographer\'s tools': '15 gp',
  'chalk': '1 cp',
  'smith\'s tools': '20 gp',
  'clothes': '15 gp',
  'brewer\'s supplies': '20 gp',
  'hammer': '1 gp',
  'banquet': '10 gp',
  'dulcimer': '25 gp',
  'disguise kit': '25 gp',
  'weaver\'s tools': '1 gp',
  'flute': '2 gp',
  'glassblower\'s tools': '30 gp',
  'bread': '2 cp',
  'mason\'s tools': '10 gp',
  'chest': '5 gp',
  'saffron': '15 gp',
  'ox': '15 gp',
  'flask or tankard': '2 cp',
  'salt': '5 cp',
  'shawm': '2 gp',
  'fishing tackle': '1 gp',
  'block and tackle': '1 gp',
  'bucket': '5 cp',
  'dragonchess set': '1 gp',
  'three-dragon ante set': '1 gp',
  'antitoxin': '50 gp',
  'ball bearings': '1 gp',
  'tinker\'s tools': '50 gp',
  'cheese': '1 sp',
  'canvas': '1 sp',
  'wheat': '1 cp',
  'barrel': '2 gp',
  'bedroll': '1 gp',
  'linen': '5 gp',
  'silk': '10 gp',
  'poisoner\'s kit': '50 gp',
  'acid': '25 gp',
  'horn': '3 gp',
  'book': '25 gp',
  'grappling hook': '2 gp',
  'lute': '35 gp',
  'climber\'s kit': '25 gp',
  'alchemist\'s fire': '50 gp',
  'caltrops': '1 gp',
  'carpenter\'s tools': '8 gp',
  'cow': '10 gp',
  'platinum': '500 gp',
  'viol': '30 gp',
  'flour': '2 cp',
  'jeweler\'s tools': '25 gp',
  'candle': '1 cp',
  'alchemist\'s supplies': '50 gp',
  'lyre': '30 gp',
  'painter\'s supplies': '10 gp',
  'woodcarver\'s tools': '1 gp',
  'potter\'s tools': '10 gp',
  'dice set': '1 sp',
  'playing card set': '5 sp',
  'herbalism kit': '5 gp',
  'wine fine': '10 gp',
  'ginger or one goat': '1 gp',
  'meat': '3 sp',
  'bottle': '2 gp',
  'goat': '1 gp',
  'pepper': '2 gp',
  'drum': '6 gp',
  'blanket': '5 sp',
  'chain': '5 gp',
  'navigator\'s tools': '25 gp',
  'backpack': '2 gp',
  'leatherworker\'s tools': '5 gp',
  'forgery kit': '15 gp',
  'bell': '1 gp'
};
