import '../../base/list_item_generator.dart';

/// A class that generates gods plan
class GodsPlanGenerator extends ListItemGenerator<String> {
  static const _plans = [
    'to reclaim their lost power and ascend to a higher realm',
    'to manipulate the elements and wreak havoc on the mortal world',
    'to intervene in mortal affairs and establish a new order of governance',
    'to punish the wicked and reward the virtuous',
    "to awaken a slumbering evil and test the mettle of the world's heroes",
    'to gather a chosen few and grant them godly powers to do their bidding',
    'to create a new pantheon of gods and overthrow the current rulers',
    'to lift a curse that has plagued the world for centuries and restore balance',
    'to teach mortals a valuable lesson by subjecting them to a divine trial',
    'to prevent an ancient prophecy from coming to fruition and plunging the world into darkness',
    'to guide mortals towards a golden age of prosperity and enlightenment',
    'to test mortals and weed out the weak from the strong',
    'to create a new race of creatures that worship them as gods',
    'to hide among mortals and rule from the shadows',
    'to pit mortals against each other in an endless cycle of war',
    'to awaken a long-dormant magic that will change the world forever',
    'to punish mortals for their hubris and arrogance',
    'to offer mortals a chance at redemption through a series of trials',
    'to manipulate the fabric of reality and reshape the world in their image',
    'to seek out and destroy powerful artifacts that threaten their power',
    'to groom a mortal hero who will one day take their place among the pantheon',
    'to gather mortal souls and create an army for the coming apocalypse',
    'to create a utopian society ruled by the divine',
    'to spread their influence throughout the cosmos and become the supreme gods of all existence',
    'to spark a revolution among the mortal races and overthrow the current order',
    'to merge their divine essence with mortal bodies and rule as god-kings',
    'to test mortals and find the one who is worthy of ascending to godhood',
    'to create a new world in their image and leave the old one to wither and die',
    'to use their powers to manipulate fate and ensure a specific outcome in mortal affairs',
    'to pit themselves against each other in a cosmic game of power and influence',
    'to build a grand temple that will serve as a gateway to their divine realm',
    'to offer their protection to a chosen mortal race in exchange for their loyalty and worship',
    'to awaken an ancient evil that will challenge mortals to their limits',
    'to transform their followers into powerful divine beings who will serve them in the afterlife',
    'to reveal themselves to mortals and demand worship and sacrifice',
    'to create a system of divine trials that mortals must complete in order to earn their favor',
    'to find a way to break the cycle of life and death and become eternal',
    'to use their power to alter the course of history and change the fate of mortals',
    'to summon powerful beings from other realms to aid them in their quest for dominance',
    'to manipulate the mortal races into warring against each other for their amusement',
    'to build a grand, celestial city that will serve as their seat of power',
    'to create a series of divine laws that mortals must follow or face punishment',
    'to create an avatar of themselves to walk among mortals and act as their emissary',
    'to use their power to end all suffering in the mortal realm',
    'to destroy mortals and start anew with a better, more obedient race',
    'to create a magical item of immense power that will cement their dominance over all other gods',
    'to hide their true intentions from mortals and manipulate them like pawns on a chessboard',
    'to pass judgment on mortals and decide their fates after death',
    'to create a divine army to vanquish a powerful foe that threatens their power',
    'to choose a mortal champion to fight in their name and carry out their will',
    'to reveal a great secret that will change the way mortals see the world and their place in it',
  ];

  GodsPlanGenerator() : super(_plans);
}
