import '../../base/list_item_generator.dart';

/// A class that generates gods fears
class GodsFearGenerator extends ListItemGenerator<String> {
  static const _plans = [
    'the return of the ancient ones',
    'the rise of a new dark lord',
    'the loss of their worshippers',
    'the end of magic',
    'the birth of a new god',
    'the destruction of their realms',
    'the coming of a great cataclysm',
    'the betrayal of one of their own',
    'the discovery of forbidden knowledge',
    'the awakening of a sleeping terror',
    'the arrival of a new age',
    'the fading of their power',
    'the corruption of their holy relics',
    'the resurrection of a fallen hero',
    'the creation of a new plane of existence',
    'the spread of an ancient curse',
    'the emergence of a new prophecy',
    'the discovery of a lost artifact',
    'the ascension of a mortal to godhood',
    'the unleashing of a powerful spell',
    'the invasion of their celestial realms',
    'the rise of a new pantheon',
    'the destruction of a powerful magical artifact',
    'the birth of a cursed child',
    'the return of a long-banished evil',
    'the fall of a great city',
    'the disappearance of a powerful cleric',
    'the emergence of a new magical force',
    'the coming of a new age of darkness',
    'the breaking of an ancient pact',
    'the darkness that lurks beyond the edge of the world',
    'the ancient curse that has plagued the land for generations',
    'the arrival of a long-forgotten prophecy',
    'the awakening of a slumbering primordial',
    'the emergence of a new race with powers beyond comprehension',
    'the impending doom of an unstoppable force',
    'the corruption that festers within the hearts of mortals',
    'the rise of a tyrannical empire with no regard for the divine',
    'the secrets that lie buried beneath the surface of the world',
    'the elusive nature of true free will',
    'the unknowable plans of the enigmatic elder beings',
    'the lure of forbidden knowledge and its catastrophic consequences',
    'the struggle for power among the deities themselves',
    'the approaching cataclysm that threatens to reshape the world',
    'the shadowy cabals that scheme behind closed doors',
    'the perils of meddling with the fabric of reality',
    'the echoes of a past that refuse to remain buried',
    'the inexorable march of time and its ultimate end',
    'the illusion of control over fate and destiny',
    'the siren song of the void and its seductive pull',
  ];

  GodsFearGenerator() : super(_plans);
}
