import '../../../../generators/generators.dart';

/// A class that generates world truths
class WorldTruthGenerator extends ListItemGenerator<String> {
  static const _truths = [
    'the conflict with the demonic hordes is escalating',
    'ancient artifacts are rumored to bring misfortune to their owners',
    'the land was once ruled by a powerful dragon',
    'there were once many more lesser deities in the pantheon',
    'members of some community secretly worship a mad god',
    'many mysterious artifacts are cursed and possess their own agendas',
    'ships that sail near the wrathful coast are frequently lost to sea',
    'the abyss is bottomless, and home to unspeakable terrors',
    'the queen\'s army includes a regiment of clockwork soldiers',
    'the forest is said to be inhabited by malevolent spirits',
    'one of the gods is slowly fading into oblivion',
    'the wild hordes seek to dominate all other races',
    'the wilderness is slowly reclaiming lost civilization',
    'not all dragons are malevolent, but many are fiercely territorial',
    'the noble families of the kingdom are searching for a way to achieve immortality',
    'the ancient temple is home to a sleeping titan',
    'the undead rise from their graves every full moon',
    'some race is master of powerful and volatile explosive technology',
    'a powerful lich lords over the dark tower in the wasteland',
    'the ancient empire collapsed due to the machinations of powerful sorcerers',
    'a secret society of the wealthy controls the political landscape',
    'the fey are fickle and their gifts are always a double-edged sword',
    'a secret island where dragons still thrive exists',
    'the great wyrm was once defeated, but will return to threaten the world again',
    'the queen is actually a powerful creature in disguise',
    'the wilds beyond the borderlands are full of all manner of monsters and bandits',
    'the ancient temple ruins hold the key to unlocking vast magical power',
    'there is a hidden network of portals that can transport travelers across great distances',
    'a powerful cult has taken root in the heart of the capital city',
    'the mountains are home to powerful giants who are fiercely territorial',
    'the great library holds secrets that could change the course of history',
    'the druids worship the spirits of nature, but some of those spirits are hostile',
    'the ancient labyrinth holds untold treasures, but also terrible dangers',
    'the nomadic tribes have mastered the art of horsemanship and mounted warfare',
    'the ancient artifacts of the ancients are the key to unlocking immense power',
    'the oracles have predicted a great cataclysm that will shake the very foundations of the world',
    'the noble houses of the kingdom are constantly plotting against one another',
    'the riverlands are home to powerful witches who can control the flow of water',
    'bandits have a vast network of underground tunnels that they use to launch sneak attacks',
    'the old hermit in the mountains holds the secret to eternal youth, but at a great cost',
    'the ancient battlefield is haunted by the spirits of the fallen',
    'the sea is home to all manner of monsters and ancient beasts',
    'the ruins of the fallen empire hold vast riches, but also unspeakable dangers',
    'the stars determine the fate of all who are born',
    'the source of all magic is a sentient crystal',
    'giants once ruled the land and may return',
    'all forests are enchanted and sentient',
    'the only way to kill a demon is to use a blessed weapon',
    'the most powerful wizards have gone insane',
    'the true rulers of the land are the elementals',
    'a great darkness approaches from the east',
    'all who enter the ancient ruins are cursed',
    'the world is flat and surrounded by an endless abyss',
    'there is a secret society of shape-shifters',
    'the moon is a prison for a powerful sorcerer',
    'all animals have the power of speech',
    'the sun will one day explode and destroy everything',
    'the gods cannot interfere directly in mortal affairs',
    'a mad god once created a chaotic realm beyond time and space',
    'all gold is cursed and will bring misfortune to its owner',
    'the greatest treasure is hidden in the realm of the dead',
    'the only way to enter the faerie realm is through a hidden portal',
    'there is a powerful artifact that can grant wishes',
    'a great dragon sleeps beneath the largest mountain',
    'there is a secret order of assassins who serve the gods',
    'the oceans are filled with monstrous sea creatures',
    'the only way to defeat a lich is to destroy its phylactery',
    'a long-forgotten civilization left behind powerful artifacts',
    'the true name of the world is known only to the gods',
    'the stars can be used to predict the future',
    'there is a hidden realm where dreams become reality',
    'the power of the gods can be stolen by mortals',
  ];

  WorldTruthGenerator() : super(_truths);
}
