import '../../../../generators/base/list_item_generator.dart';

/// A class that generates quirks of birds
class BirdQuirkGenerator extends ListItemGenerator<String> {
  static const _quirks = [
    'collects shiny objects',
    'imitates other creatures',
    'has a favorite song it constantly sings',
    'plays with its own reflection',
    'loves to hide in unexpected places',
    'gets easily distracted by insects',
    'enjoys grooming its companions',
    'has a fondness for fruit',
    'likes to rearrange its surroundings',
    'perches upside down when resting',
    'has a habit of stealing food',
    'gets cranky when disturbed during naptime',
    'obsessively arranges feathers',
    'likes to ride on other creatures',
    'constantly preens its feathers',
    'enjoys splashing in water',
    'carries small objects around',
    'performs elaborate mating dances for fun',
    'has a unique vocalization for each emotion',
    'has a fascination with clouds',
    'practices flying maneuvers in its free time',
    'has an insatiable curiosity for new things',
    'creates intricate patterns in its nest',
    'grooms other creatures it trusts',
    'observes celestial bodies with interest',
    'likes to sunbathe in the mornings',
    'comforts companions when they\'re sad',
    'collects feathers of different colors',
    'engages in mock battles with other companions',
    'likes to steal shiny objects',
    'naps with one eye open for safety',
    'performs aerial acrobatics for amusement',
    'has a playful rivalry with other companions',
    'greets the sunrise with cheerful chirping',
    'has an uncanny ability to find hidden treasures',
    'perches on the highest point it can find',
    'has a peculiar fascination with feet',
    'uses its beak to sculpt objects',
    'creates intricate patterns in the sand',
    'has an unusual sleeping schedule',
    'builds nests in peculiar locations',
    'delights in solving puzzles',
    'has an affinity for magic',
    'takes joy in sharing food with companions',
    'engages in philosophical contemplation',
    'has an unexplained fear of certain objects',
    'likes to hop around in circles',
    'has a fascination with fire',
    'likes to watch the stars at night',
    'dances to its own rhythm',
    'has a peculiar taste in food',
    'has a knack for finding hidden paths',
    'performs rituals to bring good luck',
    'has a strong sense of direction',
    'fashions nests out of flowers',
    'engages in playful banter with companions',
    'creates art with twigs and leaves',
    'plays hide and seek with its companions',
    'likes to cuddle with its companions',
    'sings lullabies to soothe its companions',
    'has a fascination with rainbows',
    'plays with its own shadow',
    'enjoys telling stories to its companions',
  ];

  BirdQuirkGenerator() : super(_quirks);
}
