import '../../base/list_item_generator.dart';

/// A class that generates durations for holidays
class HolidayDurationGenerator extends ListItemGenerator<String> {
  static const _durations = [
    "one day",
    "three days",
    "five days",
    "seven days",
    "two weeks",
    "one week",
    "a month",
    "three weeks",
    "four weeks",
    "a full season",
    "half a day",
    "a fortnight",
    "a single evening",
    "two months",
    "three months",
    "five months",
    "the entire summer",
    "the whole winter",
    "a day and a night",
    "two full days",
    "three nights",
    "dusk until dawn",
    "the time until the stars align",
    "the time until the sun sets",
    "a single night",
    "four hours",
    "three full nights",
    "one hour",
    "ten days",
    "two harvest cycles",
    "a full celestial cycle",
    "as long as the great bonfire burns",
    "a single afternoon",
    "two fortnights",
    "the night of the eclipse",
    "one moon cycle",
    "three moon cycles",
    "an entire year",
    "one season",
    "the time until the stars fade",
    "five weeks",
    "six days",
    "eight days",
    "forty days",
    "a full lunar month",
    "as long as the feast lasts",
    "two days and nights",
    "three days and nights",
    "four weeks and a day",
    "as long as the sacred flame burns",
    "one day and one night",
    "three consecutive nights",
    "six weeks",
    "nine days",
    "a single morning",
    "seven nights",
    "the duration of the high tide",
    "two nights under the stars",
    "a journey of seven days",
    "the time between sunset and sunrise",
    "two weeks and a day",
    "three seasons",
    "the time until the great hunt is complete",
    "a journey of nine days",
    "the time until the final bell rings",
    "dawn to dusk",
    "one long night"
  ];

  HolidayDurationGenerator() : super(_durations);
}
