const primordialPhysicalAppearance = [
  'towering and muscular',
  'swirling mass of elemental energy',
  'giant humanoid figure made of living stone',
  'serpentine creature',
  'massive bird of prey',
  'multi-limbed multi-eyed humanoid being',
  'amorphous blob of shifting multicolored ooze that can take any form',
  'giant and multi-legged spider',
  'towering mass of thorny vines and jagged rock',
  'massive, worm-like creature',
  'shimmering humanoid figure',
  'massive, skeletal creature',
  'humanoid made entirely of crystal',
  'hulking beast',
  'enormous, tentacled creature',
  'towering humanoid',
  'enormous dragon',
  'creature made entirely of living flame',
  'being of pure energy',
  'shapeless mass of swirling chaos',
  'being of pure darkness',
  'massive, multi-limbed creature covered in chitinous armor',
  'humanoid figure wreathed in flames',
  'being of crystalline perfection',
  'being of pure sound',
  'massive, four-legged creature',
  'being of pure light',
  'massive, insect-like creature',
  'being of pure chaos',
  'massive, amphibious creature'
];

const primordialFeatures = [
  'glowing eyes',
  'elemental aura surrounding their body',
  'skin made of living stone',
  'wings made of pure energy',
  'tentacles sprouting from their back',
  'crystals jutting out of their skin',
  'third eye in the center of their forehead',
  'crown of thorns made of living vines',
  'iridescent scales covering their body',
  "a serpent's tail instead of legs",
  'insect-like antennae on their head',
  'body made of pure water',
  'pair of horns sprouting from their forehead',
  'skin covered in glowing runes',
  'glowing orb in their chest',
  'feathers made of pure gold',
  'tentacles instead of fingers',
  'fangs made of diamond',
  'long, prehensile tongue',
  'crown made of living flame',
  'body made of swirling mist',
  'shell made of living coral',
  'extra set of eyes on their forehead',
  'tail made of living vines',
  'halo made of pure light',
  'pair of enormous wings',
  'cloak made of living shadow',
  'third, all-seeing eye in the center of their chest',
  'body made of molten lava',
  'cloak made of living leaves',
  'pair of horns made of obsidian',
  'aura of pure darkness surrounding their body',
  'pair of pincers instead of hands',
  'body made of pure wind',
  'set of gills for breathing underwater',
  'set of fins sprouting from their back'
];
