import '../../../../generators/base/list_item_generator.dart';

/// A class that generates origin for celebrations
class CelebrationOriginGenerator extends ListItemGenerator<String> {
  static const _origins = [
    'a battle between sky and earth',
    'a celestial alignment of planets',
    'a fierce battle',
    'a great battle',
    'a great flood that purified the lands',
    'a great migration to safer lands',
    'a great tidal wave that cleansed the land',
    'a heroic quest for a magical artifact',
    'a legendary duel between two warriors',
    'a legendary starfall',
    'a long-forgotten peace treaty',
    'a long-lost magical ritual',
    'a miracle rain during a great drought',
    'a mythic journey across the sea',
    'a pilgrimage',
    'a prophecy',
    'a tale of friendship',
    'a truce made between warring gods',
    'a vision of the future',
    'a vision of the great oracle',
    "an ancient goddess's blessing",
    'an ancient pact with the forest spirits',
    'the arrival of the messenger',
    'the awakening of the forest',
    'the awakening of a great beast',
    'the awakening of a great monster',
    'the banishment of a dark sorcerer',
    'the binding of the sky and earth',
    'the birth of a god',
    'the birth of the first child',
    'the blessing of the river spirits',
    'the breaking of an ancient curse',
    'the coronation of a king',
    'the crafting of a magical item',
    'the creation of the a temple',
    'the creation of a forest',
    'the day the birds returned to the land',
    'the day the sun did not rise',
    'the day the winds ceased to blow',
    'the day the wolves came to the city',
    'the defeat of a legendary monster',
    'the defeat of a plague that ravaged the lands',
    'the defeat of invaders',
    'the descent of angels',
    'the disappearance of an army',
    'the discovery of a hidden valley',
    'the discovery of an ancient map',
    'the discovery of the sacred spring',
    'the discovery of the sacred stone',
    'the emergence of the first dragons',
    'the end of a long war',
    'the falling of a massive star',
    'the final stand of the warrior king',
    'the first agreement between man and beast',
    'the first discovery of magic',
    'the first encounter with certain people',
    'the first forging of steel',
    'the first forging of the enchanted blade',
    'the first harvest',
    'the first pact with certain people',
    'the first sighting of a natural phenomenon',
    'the first song sung by the bards',
    'the first victory over the invaders',
    'the first voyage across dangerous habitat',
    'the forging of a great city',
    'the founding of the first council',
    'the founding of the first settlement',
    'the gift of fire from the gods',
    'the lighting of the eternal flame',
    'the meeting of the seven wise ones',
    'the opening of the first library',
    'the opening of the golden gate',
    'the opening of the great mountain pass',
    'the planting of the first tree',
    'the reawakening of the ancient gods',
    'the recovery of the lost scrolls',
    'the recovery of the lost treasure',
    'the return of the long-banished king',
    'the return of the long-lost heir',
    'the return of the lost kingdom',
    'the return of the lost travelers',
    'the return of the mythical phoenix',
    'the rise of the first emperor',
    'the rise of the first queen',
    'the sealing of a great evil',
    'the taming of the stormy seas',
    'the taming of the wild beasts',
    'the union of the sun and moon',
    'the union of two great tribes',
    'the unveiling of a new constellation',
    'the victory in a famous naval battle',
    'the weaving of the first spell'
  ];

  CelebrationOriginGenerator() : super(_origins);
}
