name: randpg
description: A package for generating random rpg entities. This package allows generating many random entities for rpg fantasy games, from names and npcs to entire worlds!
version: 0.9.4
repository: https://github.com/ItayElf/randpg

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
