const settlementLook = [
  "a gorgeous",
  "a beautiful",
  "a majestic",
  "an elegant",
  "a glorious",
  "an impressive",
  "a flamboyant",
  "a luxuriant",
  "a stunning",
  "an impressive",
  "a delightful",
  "a graceful",
  "a magnificent",
  "an imposing",
  "a sublime",
  "a humble",
  "a crude",
  "a rough",
  "a mediocre",
  "a dull",
  "a plain",
  "an ordinary",
  "a hideous",
  "a gruesome",
  "a dreadful",
  "a macabre",
  "a ghastly",
  "an unattractive",
  "an unexciting",
  "a worn",
  "a mundane",
];

const settlementPlace = [
  'sits on high bluffs that can only be accessed via rope elevator',
  'has a sinister reputation among the countryside',
  'is completely destitute and rundown',
  'sits in the shadow of a large ruined castle',
  'was founded on a major battle site',
  'has canals instead of streets',
  'has outlawed worship of traditional gods',
  'is divided by a river',
  'is built on a holy site',
  'is mostly a tangle of alleyways and row houses',
  'is built around a huge tree',
  'has an awful smell',
  'is the headquarters of a major family or guild',
  'is built nearby an important tomb or graveyard',
  'has an unusually wealthy population',
  'is built around a large fortress',
  'was built atop ancient ruins',
  'is built upon an isolated peak that can only be accessed by a bridge',
  'features many verdant parks and orchards',
  'was founded on a mythical or magical event',
  'is a major trade center for the surrounding area',
  'is defended by magical constructs and wards',
  'is built into the side of a mountain',
  'is the center of trade for a popular local commodity',
];

const settlementRoof = [
  "oak wood",
  "maple wood",
  "yew wood",
  "cypress wood",
  "pine wood",
  "spruce  wood",
  "redwood",
  "ash wood",
  "birch wood",
  "blackwood",
  "ebony wood",
  "elm wood",
  "ironwood",
  "mahogany wood",
  "silky oak wood",
  "willow wood",
  "bamboo",
  "shingle",
  "slate tile",
  "wheat straw",
  "sea-grass",
  "ceramic tile",
  "copper",
];

const settlementWalls = [
  "golden brick",
  "red brick",
  "redstone",
  "granite",
  "marble",
  "limestone",
  "sandstone",
  "stone veneer",
  "chiseled stone",
  "oak wood",
  "maple wood",
  "yew wood",
  "cypress wood",
  "pine wood",
  "spruce  wood",
  "redwood",
  "ash wood",
  "birch wood",
  "blackwood",
  "ebony wood",
  "elm wood",
  "ironwood",
  "mahogany wood",
  "silky oak wood",
  "willow wood",
  "bamboo",
  "shingle",
  "slate tile",
  "wheat straw",
  "sea-grass",
  "ceramic tile",
  "copper",
  "lava-stone",
];

const settlementFeature = [
  "luscious gardens",
  "enchanting wildlife",
  "swarms of fireflies",
  "babbling creeks",
  "vibrant, rare trees",
  "a breathtaking waterfall",
  "calm and quiet collection of ponds",
  "frozen lakes",
  "a frozen waterfall",
  "an imposing glacier",
  "ambient light of nearby lava streams",
  "the native bird species",
  "rainbow of different flowers",
  "an ever-clear night sky",
  "a huge, majestic geyser",
  "a silent mountain range",
  "foggy fields",
  "a gorgeous mirror lake",
  "rows upon rows of luscious trees",
  "a staircase of waterfalls",
  "frozen ponds",
  "aromatic flowers",
  "a calming ocean front",
  "fields of farmland",
  "a bamboo forest",
  "a huge oak tree",
  "a stunning canyon",
  "majestic fjords",
  "white, sandy beaches",
  "amazing sunsets",
];

const settlementAtmosphere = [
  "an amusing",
  "a captivating",
  "a charming",
  "a delightful",
  "an enchanting",
  "an enthralling",
  "an entrancing",
  "a fascinating",
  "a glamorous",
  "an heavenly",
  "an intriguing",
  "an inviting",
  "a magical",
  "a mystical",
  "a mythical",
  "an otherworldly",
  "a pleasant",
  "a pleasing",
];

const settlementSpecialty = [
  'having powerful guilds',
  'its salt mines',
  'its artists and writers',
  'its cheeky populace',
  'its cordial populace',
  'its charitable populace',
  'having delicious cuisine',
  'its blunt populace',
  'its ruthless mercenaries',
  'its quarries',
  'being the home of a great hero',
  'its greedy merchants',
  'its polite populace',
  'dark magic',
  'its kind populace',
  'its lush farmland',
  'its colorful dyes',
  'its courteous populace',
  'its skilled craftsmen',
  'its boorish populace',
  'its precious gems',
  'its medicinal plants',
  'its tolerant populace',
  'its devout populace',
  'its short populace',
  'having exotic spices',
  'its rude populace',
  'having hordes of beggars',
  'its surly populace',
  'its productive ironworks',
  'its vulgar populace',
  'its nice populace',
  'its friendly populace',
  'having high fashion',
  'its decadence',
  'its patriotism',
  'its gambling',
  'its mines and industry',
  'its strong drinks',
  'its potent herbs',
  'its crude populace',
  'its wines',
  'its uncouth populace',
  'its tall populace',
  'its suspicious populace',
  'its rowdy populace',
  'its neighborly populace',
  'its sturdy arms & armors',
  'its bad-mannered populace',
  'its energetic horses',
  'having tough warriors',
  'its political intrigue',
  'its flowers',
  'its gruff populace',
  'its heavy-handed guards',
  'having good education',
  'its tasty fish',
  'its civil populace',
  'its piety',
  'its lumber and forestry'
];

const settlementRaceRelationship = [
  'the <RACE> oppress the minority races in the <TYPE>',
  'the <RACE> are conquerors of the other races in the <TYPE>',
  'there is some tension between the races in the <TYPE>',
  'the races in the <TYPE> live together mostly in harmony',
  'there is some tension between the races in the <TYPE>',
  'the races in the <TYPE> live together mostly in harmony',
  'there is some tension between the races in the <TYPE>',
  'the races in the <TYPE> live together mostly in harmony',
];
