import '../../../../generators/base/list_item_generator.dart';

/// A class that generates mountain features
class MountainFeatureGenerator extends ListItemGenerator<String> {
  static const _features = [
    'are made of glowing crystals',
    'are sentient and can move on their own',
    'are inhabited by giant creatures',
    'are hollow and home to an underground city',
    'have hidden ancient ruins at their summit',
    'are constantly shifting and changing shape',
    'are surrounded by a perpetual storm',
    'have a lake or ocean at their base that is home to sea monsters',
    'have giant statues carved into their sides',
    'are imbued with magical properties that affect the surrounding area',
    'have a network of underground tunnels and passageways',
    'are home to a dragon or other powerful guardian creature',
    'are made of crystal that hums with energy and can be used for magical purposes',
    'are the source of a powerful elemental force',
    'are home to a mystical order of monks or sages',
    'have a series of natural hot springs with healing properties',
    'are said to contain a secret treasure or artifact of immense power',
    'are sacred or revered by a particular culture or religion',
    'are the site of an important historical battle or event',
    'have hidden valleys or plateaus at high altitudes, untouched by civilization',
    'are surrounded by a magical aura that causes strange phenomena',
    'are the source of a valuable resource that is fiercely guarded by powerful entities',
    'are surrounded by other natural features',
    'are flanked by a network of winding mountain passes and treacherous trails',
    'feature a diverse range of elevations, with peaks ranging from low to high',
    "are active volcanos",
    "are made out of black stone",
    "are made out gray stone",
    "are covered by short vegetation",
    "are dormant volcanos",
    'are towering spires of jagged rock',
    'are shrouded in mist and fog',
    'are snow-capped year-round',
    'have sheer cliffs and narrow ridges',
    'are surrounded by deep canyons',
    'are home to hot springs and geysers',
    'are covered in dense forests at the base',
    'are honeycombed with caves and tunnels',
    'are dotted with crystal-clear alpine lakes',
    "are home to hot springs and geysers",
    "are covered in dense forests up to a certain elevation",
    "have steep and winding roads leading to the summit",
    "have hidden caves and tunnels within their depths",
  ];

  MountainFeatureGenerator() : super(_features);
}
