import '../../../../generators/base/list_item_generator.dart';

/// A class that generates quirks of dogs
class DogQuirkGenerator extends ListItemGenerator<String> {
  static const _quirks = [
    'hides clothes under the bed',
    'chases shadows',
    'snores loudly',
    'whines when left alone',
    'steals food',
    'burrows under blankets',
    'has a favorite toy that never leaves their side',
    'sits on your feet',
    'wiggles butt when excited',
    'licks everything',
    'grabs attention with a paw',
    'chases their own tail',
    'talks back',
    'begs for belly rubs',
    'obsesses over squirrels',
    'digs holes everywhere',
    'howls at the moon',
    'buries various items',
    'sits in strange places',
    'licks faces excessively',
    'likes to nap in the sun',
    'spins in circles before lying down',
    'brings gifts to visitors',
    'insists on sitting in laps',
    'sleeps with eyes open',
    'tries to fit in small spaces',
    'herds other pets or children',
    'sits like a human',
    'whimpers in their sleep',
    'inspects new objects with caution',
    'chews on furniture legs',
    'wakes up with the sunrise',
    'tilts head when curious',
    'inspects their reflection in mirrors',
    'sneezes when excited',
    'dances on hind legs',
    'perks up ears at strange noises',
    'licks toes',
    'sniffs everything on walks',
    'sings along with music',
    'chases birds',
    'howls when left alone',
    'chases reflections',
    'stares at someone until they pet them',
    'tries to catch flies',
    'stands on hind legs to beg for treats',
    'gives high fives',
    'spins in circles when excited',
    'naps in weird positions',
    'sits on your feet to keep them warm',
    'snores with mouth open'
  ];

  DogQuirkGenerator() : super(_quirks);
}
