import '../../../../generators/base/list_item_generator.dart';

/// A class that generates skills of birds
class BirdSkillGenerator extends ListItemGenerator<String> {
  static const _skills = [
    'emitting piercing screeches to intimidate foes',
    'camouflaging to blend seamlessly into surroundings',
    'moving with stealth and agility to avoid detection',
    'skilfully catching fish from water bodies',
    'flocking together for increased safety',
    'launching surprise attacks from concealed positions',
    'intimidating adversaries with imposing presence',
    'keeping watch over allies with sharp eyes',
    'skillfully foraging for scarce resources',
    'distracting enemies with dazzling displays',
    'gliding effortlessly on air currents',
    'gathering valuable resources for the group',
    'surveying the terrain for potential dangers',
    'herding prey into advantageous positions',
    'escaping from dangerous situations with speed',
    'finding secure roosting spots for rest',
    'executing precise aerial dives to catch prey',
    'singing beautiful melodies to uplift spirits',
    'trapping prey with cunning strategies',
    'mastering the art of celestial navigation',
    'delivering messages swiftly and accurately',
    'flanking opponents to gain strategic advantage',
    'swooping down to snatch prey with swift precision',
    'efficiently delivering messages across long distances',
    'mastering the art of flight in various conditions',
    'exploring unknown territories with curiosity',
    'ambushing unsuspecting targets with precision',
    'evading capture with nimble movements',
    'maintaining vigilant surveillance over territory',
    'building sturdy nests with intricate designs',
    'hovering in place to observe surroundings',
    'defending territory with unwavering courage',
    'mimicking a wide range of sounds and voices',
    'coordinating efforts with companions for success',
    'swiftly dodging incoming attacks',
    'protecting allies from potential threats',
    'communicating complex messages effectively',
    'creating detailed maps of the landscape',
    'conducting reconnaissance missions from the air',
    'conducting thorough reconnaissance missions',
    'transporting objects or messages over distances',
    'tracking elusive targets with precision',
    'expertly hunting small game for sustenance',
    'finding secure perches for resting and observation',
    'creating diversions to confuse adversaries',
    'snatching objects from unsuspecting targets',
    'alerting allies to approaching danger',
  ];

  BirdSkillGenerator() : super(_skills);
}
