import '../../../../generators/base/list_item_generator.dart';

/// A class that generates specialties of a druid circle
class DruidsSpecialtyGenerator extends ListItemGenerator<String> {
  static const _specialties = [
    'nature conservation and restoration',
    'healing and herbology',
    'animal husbandry and care',
    'weather manipulation and control',
    'geomancy and earth magic',
    'elemental summoning and control',
    'warding and protection spells',
    'divine blessings and invocations',
    'spiritual guidance and counseling',
    'herbal remedies and tonics',
    'elemental lore and knowledge',
    'natural disaster response and relief',
    'weather forecasting and prediction',
    'water purification and cleansing',
    'druidic prophecy and divination',
    'shapeshifting and animal forms',
    'sacred grove and forest management',
    'earthquake detection and prevention',
    'elemental balancing and alignment',
    'plant-based dyes and pigments',
    'tree-houses',
    'druidic poetry and storytelling',
    'animal tracking',
    'star and celestial navigation',
    'spirit animal communication and bonding',
    'druidic astrology',
    'geothermal energy harvesting and management',
    'crystal healing and therapy',
    'bioluminescent plant cultivation',
    'dream interpretation and analysis',
    'spiritual vision quests and journeys',
    'elemental fusion and alchemy',
    'druidic wedding ceremonies and rites of passage',
    'spirit animal totem carving and artistry',
    'storm chasing and observation',
    'elemental spirit summoning and control',
    'sacred site protection and management',
    'elemental resistance and adaptation',
    'plant-based armor and weaponry',
    'druidic battle tactics and strategies',
    'spiritual cleansing and purification',
    'forest therapy and nature immersion',
    'elemental harmony and cooperation',
    'druidic meditation and mindfulness',
    'solar and lunar energy manipulation',
    'nature-based poetry and literature',
    'elemental myth and legend interpretation',
  ];

  DruidsSpecialtyGenerator() : super(_specialties);
}
