const monumentBuildTime = [
  "100 years",
  "over 100 years",
  "a century",
  "over a century",
  "decades",
  "a few decades",
  "a decade",
  "a few dozen years",
  "generations",
  "nearly 500 years",
  "about 400 years",
  "almost 200 years",
  "only a few years",
  "a generation",
  "only a handful of years",
  "about a dozen years",
  "only half a dozen years",
  "about 50 years",
  "about 75 years",
  "about 25 years",
];

const monumentType = [
  "statue",
  "group statue",
  "art piece",
  "monolith",
  "obelisk",
  "triumphal arch",
  "terminating vista",
  "mound",
  "eternal flame",
  "column",
  "column arrangement",
  "cenotaph",
  "shrine",
  "fountain",
];

const monumentLocation = [
  "the grand plaza",
  "the town center",
  "the peak of a main hill",
  "the park's center",
  "the main park",
  "the settlement's main entrance",
  "the settlement hall",
  "the market center",
  "the outskirts of the settlement",
  "the small park",
  "the settlement gates",
  "the settlement's center",
  "a river side",
  "a quiet shore",
  "the botanical garden",
  "the tallest hillside",
  "the middle of a lake",
  "an island inside a lake",
  "the waterfall's base",
  "the floral park",
  "the art district",
  "the business center",
  "the temple plaza",
  "the palace entrance",
  "the grand park",
  "a river's quiet side",
  "the forest entrance",
  "a park entrance",
  "the national park",
  "the library",
  "the graveyard entrance",
  "the main crossroads",
  "the old town center",
  "the farmland limits",
  "the harbor entrance",
  "the main bridge's entrance",
  "the cultural center",
  "the shopping district",
  "the old settlements entrance",
  "the old town hall",
];

const monumentPurpose = [
  "how easily life can turn for the worst, as it has for the people in the past",
  "the atrocities committed during earlier ages and the struggles the people went through",
  "the struggles and sacrifices made during the cruel revolution that changed the region",
  "the struggles past generations have gone through to better life of future generations",
  "the struggles the people of this region have gone through throughout the ages",
  "a great leader whose life was unfortunately ended abruptly by opposing forces",
  "each new generation and the advances brought by each of them across time",
  "the freedom gained after a terrible war and the overthrowing of tyranny",
  "the freedoms the people of this region have had for so many years and the progress it brought with it",
  "the great health care and the eternal search for the improvement of care for all",
  "the heroic child who managed to save hundreds of life during a natural disaster",
  "the ingenuity and creativity of the people of this region throughout the ages",
  "the leaders who lead by being a great example for all and changed the world for the better",
  "the lives of all those who have made this region as great as it is today",
  "the love between two monarchs from two completely different worlds and the unity they brought",
  "the loving families and great family care this region is proudly known for",
  "the natural wonders and beauty this region has offered for centuries and helped the people flourish",
  "the peaceful life this region is known for and has upheld for so many years",
  "the people working in protection services and all the great work they've provided throughout the years",
  "the revolution that changed life for the better for the people in this region",
  "the rich and diverse cultural history of this region and its people throughout the ages",
  "the rich musical and artistic history of this region, which is still part of it today",
  "the rich traditions and customs from the past still alive to this day",
  "the safety and serenity of this region, which has been the standard for so long",
  "the solidarity and harmonic way the people of this region live with each other",
  "the strength and perseverance of the people of this region, no matter the times",
  "the unity of the people and how it helped them through rough times and thrive in better times",
  "the ways the people in this region have always overcome struggles in the past",
  "a single hero whose life was lost after saving the lives of many others in a freak fire",
  "all the civilians who fought, worked and sacrificed all during the terrible war",
  "all those who dedicate their lives to the protection of everybody else",
  "soldiers of all ages whose sacrifices have made sure life is as good as it is today",
  "the brave sacrifices made by tens of thousands of soldiers during the grand war",
  "the people who fought tyranny and those who continue to do so to this day",
  "the people who stood up for what they believed in and paid for it with their lives during darker times",
  "the poor families who lost everything during the terrible fire that burned down countless homes",
  "the sacrifices of the lower classes during the darker times, but on which much has been built",
  "a religious deity and is meant to guard over this region and its people",
  "both the struggles and victories of the people during the brutal war of the past",
  "life itself and the way different paths intertwine and often lead to similar outcomes",
  "the blooming of this region during earlier ages and the echoes of it still visible today",
  "the hopes and dreams of the people of this region and the promise each new generation brings",
  "the importance of all generations, both young and old, and what they have to offer",
  "the overcoming of evil, as has been done several times in the past during darker times",
  "the progress made by this region throughout the ages and the hopes for the future",
  "the search for progress and knowledge the people of this region are known for",
  "the self reliance and independence this region has been built on and thrived on",
  "the spirituality and culture from the past and its influence on life today",
  "the virtues of the people which have brought them through both rough and great times alike",
  "the way the people of this region have always looked after each other for generations",
];

const monumentRepresenting = [
  "heart and soul of the people and the unbreakable bond between past and future generations",
  "backbone of the community and is a symbol of strength and perseverance",
  "strong bond this community has with both its people and its surroundings",
  "strong mind and balanced way of life this community strives for",
  "intertwining of all lives in this community and the strength that comes with unity",
  "strong unity of this community and the way everybody is almost considered as one big family",
  "powerful bond between past, present and future generations throughout the ages",
  "blooming of life, as well as its fragility and strength in different aspects and periods",
  "light and darkness in life and how it's present across time",
  "delicate balance of life and how it seems to shift forever throughout time",
  "foundations of this community and the continuation of growth throughout time",
  "beating heart of the people and all their dreams and aspirations for the future",
  "collective mind of the people and their goals in life for themselves and this community",
  "flow of time and the progress the people of this community continue to make",
  "beating heart of this community and how its energy flows across this region",
  "soul of this community and the importance of togetherness and looking out for each other",
  "creative spirit of this community and how it affected and continues to affect life",
  "working hands of the people and how their work continues to be the foundation of life here",
  "brilliant minds of the people and how their ingenuity helped shape life throughout time",
  "blossoming of both life and the community here throughout all periods of time",
];

const monumentCreator = [
  "a local artist",
  "a famous national artist",
  "an upcoming local artist",
  "an upcoming national artist",
  "a famous international artist",
  "an upcoming international artist",
  "an international artist",
  "a national artist",
  "a young artist",
];

const monumentAdjective = [
  "accurately",
  "perfectly",
  "admirably",
  "superbly",
  "flawlessly",
  "wonderfully",
  "exquisitely",
  "marvelously",
  "strikingly",
  "spectacularly",
];

const monumentCaptured = [
  "cultural influences of the region",
  "cultural history of the region",
  "varied history of the region",
  "natural influences of the region",
  "natural beauty of the region",
  "rich history of the region",
  "people's pride",
  "people's joy",
  "people's love",
];

const monumentStyle = [
  "a classical",
  "a clean",
  "a complex",
  "a glamorous",
  "a harmonious",
  "a humble",
  "a lavish",
  "a minimalistic",
  "a modest",
  "a personal",
  "a pure",
  "a regional",
  "a rustic",
  "a simplistic",
  "a smooth",
  "a sophisticated",
  "an abstract",
  "an elaborate",
  "an elegant",
  "an expressionistic",
  "an intricate",
  "an ornate",
];

const monumentMaterials = [
  "durable",
  "dependable",
  "reliable",
  "deluxe",
  "superior",
  "lavish",
  "exceptional",
  "high quality",
  "premium",
  "high-class",
];

const monumentPresent = [
  "easily stand the tests of time with minimal maintenance",
  "continue to provide local jobs whenever it needs maintenance",
  "stand the tests of time and continue to bring joy",
  "stand the tests of time and be part of the community for ages",
  "continue to be a proud part of this community for generations",
  "be an integral part of this community for many generations more",
  "continue to provide joy and wonder to this community for ages",
  "require minimum maintenance while still upholding a great look",
  "continue to uplift spirits with minimum maintenance requirements",
  "continue to adorn the community for generations to come",
  "continue to decorate the community while requiring minimum maintenance",
  "continue to both decorate the community and provide local maintenance jobs",
  "remain an important aspect of the community spirit for many more years",
  "uphold local values and customs for generations to come",
  "remain an inspiration source for generations to come",
];
