import '../../base/list_item_generator.dart';

class SettlementTroubleGenerator extends ListItemGenerator<String> {
  static const _troubles = [
    'outsiders rejected',
    'dangerous discovery',
    'dreadful omens',
    'natural disaster',
    'old wounds reopened',
    'important object is lost',
    'someone is captured',
    'mysterious phenomenon',
    'revolt against a leader',
    'vengeful outcast',
    'rival settlement',
    'nature strikes back',
    'someone is missing',
    'production halts',
    'mysterious murders',
    'debt comes due',
    'unjust leadership',
    'disastrous accident',
    'in league with the enemy',
    'raiders prey on the weak',
    'cursed past',
    'an innocent is accused',
    'corrupted by dark magic',
    'isolated by brutal weather',
    'provisions are scarce',
    'sickness run amok',
    'allies become enemies',
    'attack is imminent',
    'lost caravan',
    'dark secret revealed',
    'urgent expedition',
    'a leader falls',
    'families in conflict',
    'incompetent leadership',
    'reckless warmongering',
    'beast on the hunt',
    'betrayed from within',
    'broken truce',
    'wrathful haunt',
    'conflict with firstborn',
    'trade route blocked',
    'in the crossfire',
    'stranger causes discord',
    'important event threatened',
    'dangerous tradition'
  ];

  SettlementTroubleGenerator() : super(_troubles);
}
