import '../../../../generators/base/list_item_generator.dart';

/// A class that generates quirks of monkeys
class MonkeyQuirkGenerator extends ListItemGenerator<String> {
  static const _quirks = [
    'steals food',
    'throws objects',
    'grooms everyone',
    'hoards shiny things',
    'swings from furniture',
    'mimics sounds',
    'plays with its tail',
    'watches people curiously',
    'hides in high places',
    'fiddles with zippers',
    'peeks around corners',
    'makes funny faces',
    'chitters loudly when excited',
    "tugs on people's clothes",
    "climbs on people's shoulders",
    'fascinated by reflections',
    'steals hats',
    'loves to drum on objects',
    'balances on one leg',
    'swipes snacks from plates',
    'hides small objects',
    'loves playing with ropes',
    'dangles upside down',
    'throws food when angry',
    'pulls on hair',
    'drums on surfaces with hands',
    'dances when excited',
    'loves to splash water',
    'jumps unexpectedly',
    'hangs from curtains',
    'snatches things from bags',
    'makes clicking sounds',
    'loves to imitate gestures',
    'runs in circles when happy',
    'pokes things with sticks',
    'sits in strange positions',
    'grabs shiny objects',
    'teases other pets',
    'climbs bookshelves',
    'watches TV intently',
    'chews on random objects',
    'pokes at insects',
    'sleeps in hammocks',
    'watches people eat',
    'hoards food for later',
    'darts between legs',
    'bounces off walls',
    'nibbles on plants',
    'hides in tight spaces',
    'pulls faces at mirrors',
    'throws things off tables',
    'wakes up at odd hours',
    'spins in circles',
    'stares at the sky',
    'loves to tug on blankets',
    'plays with shadows',
  ];

  MonkeyQuirkGenerator() : super(_quirks);
}
