import '../../../../generators/base/list_item_generator.dart';

/// A class that generates skills of imps
class ImpSkillGenerator extends ListItemGenerator<String> {
  static const _skills = [
    'casting spells to manipulate luck',
    'summoning familiars to aid in tasks',
    'casting dark magic',
    'conjuring ghostly apparitions',
    'casting spells of manipulation',
    'casting spells of enchantment',
    'climbing walls and ceilings',
    'casting spells to create illusions of treasure',
    'casting shadow magic',
    'casting spells of evasion',
    'summoning spectral allies',
    'casting spells of deception',
    'casting spells to summon spectral weapons',
    'casting spells of darkness',
    'whispering curses to afflict foes with nightmares',
    'manipulating magical energies',
    'casting spells of mischief',
    'casting spells to drain life force',
    'casting spells of chaos',
    'creating magical barriers',
    'conjuring traps from shadows',
    'casting protective wards',
    'manipulating emotions to sow discord',
    'spreading rumors to sow discord',
    'finding hidden treasures',
    'brewing potions to induce sleep',
    'casting minor spells',
    'casting spells of distraction',
    'conjuring illusions of vast riches',
    'casting spells to manipulate time',
    'stealing memories',
    'summoning creatures to distract enemies',
    'casting spells to amplify fear',
    'casting spells of illusion',
    'casting spells of stealth',
    'channeling dark energy to enhance spells',
    'spreading rumors and lies',
    'whispering sinister thoughts',
    'casting spells of discord',
    'finding hidden knowledge',
    'communicating with animals',
    'casting spells to incite chaos',
    'manipulating dreams to influence actions',
    'conjuring illusions of monstrous creatures',
    'casting enchantments',
    'manipulating emotions',
    'channeling energy to heal allies',
    'casting spells to confuse adversaries',
    'stealthy movement',
    'pilfering valuable items',
    'disguising their presence',
    'casting spells to manipulate elements',
    'creating magical traps',
    'casting spells of theft',
    'detecting magical auras',
    'tracking targets',
    'casting spells of trickery',
    'channeling energy to create protective barriers',
    'manipulating shadows to cloak allies',
    'casting spells of luck',
    'conjuring small flames',
    'communicating with spirits to gain knowledge',
    'casting hexes',
    'brewing potions',
    'enhancing stealth abilities',
    'casting spells of sleep',
    'casting spells of silence',
    'casting spells to animate objects',
    'conjuring magical traps from thin air',
    'casting curses',
    'reading ancient texts',
    'manipulating shadows to conceal allies',
    'casting spells of subterfuge',
    'casting spells of fear',
    'shapeshifting into small creatures',
    'finding hidden paths',
    'casting spells to steal thoughts',
    'brewing poisons',
    'disguising themselves',
    'casting spells of madness',
    'creating illusions of false treasure',
    'brewing potions to enhance stealth',
    'casting spells of confusion',
    'casting spells of sabotage',
    'casting spells of misdirection',
    'casting spells to summon storms',
    'eavesdropping on conversations',
    'manipulating dreams',
    'creating illusions to deceive enemies',
    'casting minor illusions',
    'brewing poisons to incapacitate enemies',
    'creating distractions',
    'whispering curses to weaken foes',
    'creating wards to protect allies',
    'summoning small creatures',
    'casting spells of invisibility',
    'picking locks',
    'casting spells to disrupt magical rituals',
    'casting spells of protection',
    'brewing potions to enhance abilities',
    'spying on enemies',
    'sneaking past guards',
    'creating illusions to confuse enemies'
  ];

  ImpSkillGenerator() : super(_skills);
}
