const genericSpecialFeatures = [
  'is very nimble',
  'is very clumsy',
  'gestures profusely during a conversation',
  'has a high-pitched voice',
  'has a low-toned voice',
  'is easily out of breath',
  'has a sunken breastbone',
  'cannot whistle',
  'smells of alcohol',
  'smells of unwashed clothes',
  'smells of expensive cologne',
  'smells of the sea',
  'is blind',
  'is mute',
  'is missing a leg',
  'is missing a hand',
  'has long fingers',
  'has a tattoo on his left hand',
  'has a tattoo on his right hand',
  'has a tattoo on his left leg',
  'has a tattoo on his right leg',
  'has a tattoo',
  'has a scar',
  'is slightly colorblind',
  'has extremely long nails',
  'has an allergy',
  'wears an eye-patch',
  'walks with a pronounced limp',
  'carries a mysterious pendant',
  'has a pet familiar that never leaves their side',
  'always wears gloves, regardless of the weather',
  'possesses an uncanny ability to mimic voices',
  'has a perpetually furrowed brow',
  'speaks in riddles and metaphors',
  'always wears a wide-brimmed hat',
  'bears a striking resemblance to a famous historical figure',
  'has a tendency to hum or sing softly while working',
  'wears mismatched socks or shoes',
  'has a pet raven that delivers messages',
  'carries a collection of intricate, hand-carved wooden figurines',
  'speaks in a rapid manner',
  'has a habit of fidgeting with small objects',
  'has an affinity for speaking in rhymes',
  'wears an enchanted amulet that glows in the dark',
  'has a distinctive birthmark on their face',
  'wears a necklace made of polished stones',
  'has a pocketful of colorful, magical marbles',
  'speaks in a whisper, even in crowded places',
  'has a pet snake that coils around their arm',
  'carries a worn, leather-bound journal filled with sketches',
  'wears a mask to conceal their true identity',
  'has an affinity for telling elaborate stories',
  'always carries a small vial of sparkling dust',
  'possesses a magical compass that always points north',
  'wears a necklace of teeth from different creatures',
  'speaks with an accent from a distant land',
  'carries a bag of enchanted marbles that can change color',
  'always wears a cloak that billows dramatically in the wind',
  'wears a pair of enchanted spectacles that reveal hidden messages',
  'possesses a set of enchanted dice that always roll high numbers',
  'has a penchant for playing practical jokes on others',
  'carries a small, talking stuffed animal as a companion',
  'speaks in a singsong voice, as if constantly in song',
  'always wears a necklace of dried herbs and flowers',
  'possesses a magical quill that writes with invisible ink'
];
