const genericSpecialFeatures = [
  'is very nimble',
  'is very clumsy',
  'gestures profusely during a conversation',
  'has a high-pitched voice',
  'has a low-toned voice',
  'is easily out of breath',
  'has a sunken breastbone',
  'cannot whistle',
  'smells of alcohol',
  'smells of unwashed clothes',
  'smells of expensive cologne',
  'smells of the sea',
  'is blind',
  'is mute',
  'is missing a leg',
  'is missing a hand',
  'has long fingers',
  'has a tattoo on his left hand',
  'has a tattoo on his right hand',
  'has a tattoo on his left leg',
  'has a tattoo on his right leg',
  'has a tattoo',
  'has a scar',
  'is slightly colorblind',
  'has extremely long nails',
  'has an allergy',
];
