import '../../base/list_item_generator.dart';

/// A class that generates things a kingdom is known for
class KingdomKnownForGenerator extends ListItemGenerator<String> {
  static const _knownFor = [
    'a powerful military force',
    'beautiful architecture and cityscapes',
    'a famous university or academy',
    "the world's largest library or archive",
    'an abundance of magical creatures',
    'fine arts and cultural achievements',
    'exceptional cuisine and food traditions',
    'a bustling marketplace or trade hub',
    'a dark and mysterious past',
    'advanced technology or weaponry',
    'pristine natural landscapes and wildlife',
    'a famous wizard or sorcerer',
    'a rich and diverse religious history',
    'renowned musicians and entertainers',
    "the world's largest mine or quarry",
    'a deep and complex political system',
    'exceptional shipbuilding and naval prowess',
    'a famous festival or celebration',
    'a history of powerful monarchs or rulers',
    'an ancient and powerful artifact',
    'exceptional medical and healing practices',
    'a famous landmark or monument',
    'a history of rebellion and uprisings',
    'a strong tradition of storytelling and literature',
    'exceptional blacksmithing and metalworking',
    'a famous wizarding academy or school of magic',
    'a rich and diverse system of laws and justice',
    'renowned artists and craftsmen',
    "the world's largest trade fleet",
    'a history of heroic and legendary figures',
    'exceptional glassmaking and crystalwork',
    'a famous arena or stadium for sports and entertainment',
    'a history of war and conquest',
    'a strong tradition of hospitality and tourism',
    'renowned architects and builders',
    "the world's largest network of tunnels or catacombs",
    'a famous circus or traveling show',
    'a rich and diverse system of languages and dialects',
    'exceptional gem-cutting and jewelry-making',
    'a history of isolationism and xenophobia',
    'a strong tradition of education and learning',
    'renowned brewers and distillers',
    "the world's largest network of canals or waterways",
    'a famous pilgrimage site or religious destination',
    'a history of plague and disease',
    'a strong tradition of exploration and discovery',
    'exceptional leatherworking and tanning',
    'a famous clock or timekeeping device',
    'a rich and diverse system of heraldry and symbols',
    "the world's largest collection of rare and exotic artifacts"
  ];

  KingdomKnownForGenerator() : super(_knownFor);
}
