import '../../../../generators/base/list_item_generator.dart';

/// A class that generates skills of dogs
class DogSkillGenerator extends ListItemGenerator<String> {
  static const _skills = [
    'tracking',
    'hunting',
    'scenting',
    'guarding',
    'scouting',
    'herding',
    'sneaking',
    'swimming',
    'climbing',
    'digging',
    'intimidating',
    'ambushing',
    'communicating silently',
    'finding hidden objects',
    'distracting enemies',
    'finding water sources',
    'following trails',
    'disarming traps',
    'attacking on command',
    'carrying messages',
    'finding edible plants',
    'rescuing trapped individuals',
    'alerting to danger',
    'hiding and remaining still',
    'working in tandem with other animals',
    'snatching objects quickly',
    'navigating through rough terrain',
    'blending into surroundings',
    'creating diversions',
    'scaling walls or cliffs',
    'withstanding extreme temperatures',
    'finding shelter',
    'sensing upcoming weather',
    'detecting magic',
    'predicting natural disasters',
    'rescuing drowning individuals',
    'recognizing medicinal plants',
    'coordinating group tactics',
    'detecting illusions',
    'stealing items without being noticed',
    'avoiding traps',
    'navigating through dense forests',
    'finding hidden passages',
    'concealing its presence',
    'learning and executing complex commands',
    'sensing disturbances in the environment',
    'retrieving objects from difficult places',
    'hearing beyond normal range',
    'finding rare ingredients',
    'assisting in rituals',
    'keeping watch over sleeping companions',
    'detecting poison',
    'aiding in navigation',
    'forging paths through dense vegetation',
    'enduring long journeys',
    'surviving in harsh environments',
    'spotting distant threats',
    'locating lost items',
    'sensing impending danger',
    'navigating underground tunnels',
    'assisting in reconnaissance missions',
    'understanding ancient symbols',
    'guiding lost travelers',
    'detecting invisible entities',
    'scouting enemy movements',
    'guiding through treacherous waters',
    'sensing disturbances in the air',
    'finding hidden chambers',
    'retrieving stolen goods',
  ];

  DogSkillGenerator() : super(_skills);
}
