import '../../../../generators/base/list_item_generator.dart';

/// A class that generates quirks of cats
class CatQuirkGenerator extends ListItemGenerator<String> {
  static const _quirks = [
    'chases shadows',
    'loves belly rubs',
    'collects shiny objects',
    'falls asleep in strange places',
    'talkative',
    'plays fetch with small objects',
    'fascinated by water',
    'gets into bags and boxes',
    'curls up in unusual positions',
    'always seeks warmth',
    'paw massages',
    'greets with headbutts',
    'demands attention',
    'follows owner everywhere',
    'steals food',
    'lays on paper',
    'holds conversations with birds outside',
    'always wants to be held',
    'loves to climb to high places',
    'excessive grooming',
    'likes to hide in small spaces',
    'begs for treats',
    'plays with own tail',
    'wakes owner up early for breakfast',
    'cuddles with other pets',
    'plays with its own reflection',
    'always hungry',
    'chews on plants',
    'pounces on unsuspecting objects',
    'knocks things off tables',
    'licks windows',
    'sits on shoulders',
    'licks owner\'s hair',
    'plays hide and seek',
    'has a favorite toy',
    'chases insects',
    'sits on top of doors',
    'knocks on doors',
    'likes to be carried around',
    'steals clothes',
    'begs for attention when eating',
    'watches owner eat',
    'chases its own tail',
    'sits in baskets',
    'snores loudly',
    'picks favorite spots in the house',
    'loves to be brushed',
    'gets into empty boxes',
    'has a fascination with feet',
    'plays dead',
    'sits on bookshelves',
    'knocks over houseplants',
    'likes to roll in dirt',
    'steals food off plates',
    'runs around the house at night',
    'plays with its own shadow',
    'sleeps on top of doors',
    'watches birds outside',
    'chases after bugs'
  ];

  CatQuirkGenerator() : super(_quirks);
}
