const guildTraits = [
  "skill",
  "cunning",
  'adaptability',
  'agility',
  'ambition',
  'bravery',
  'camaraderie',
  'charisma',
  'charm',
  'confidence',
  'cooperation',
  'courage',
  'creativity',
  'determination',
  'discipline',
  'expertise',
  'focus',
  'honor',
  'humility',
  'ingenuity',
  'innovation',
  'integrity',
  'intelligence',
  'leadership',
  'loyalty',
  'mental fortitude',
  'patience',
  'perception',
  'perseverance',
  'physical strength',
  'quick thinking',
  'resilience',
  'resourcefulness',
  'ruthlessness',
  'stealth',
  'strategy',
  'tactfulness',
  'tenacity',
  'unity',
];

const guildAction = [
  'adapt',
  'amplify',
  'build',
  'challenge',
  'champion',
  'collaborate',
  'communicate',
  'create',
  'cultivate',
  'develop',
  'drive',
  'elevate',
  'empower',
  'encourage',
  'engage',
  'enhance',
  'expand',
  'explore',
  'facilitate',
  'foster',
  'influence',
  'initiate',
  'innovate',
  'inspire',
  'lead',
  'motivate',
  'optimize',
  'organize',
  'overcome',
  'persist',
  'pioneer',
  'pursue',
  'refine',
  'refocus',
  'solve',
  'strategies',
  'streamline',
  'strengthen',
  'support',
  'sustain',
  'transform',
  'unite',
];

const guildGoals = [
  'achieve greatness',
  'protect our people',
  'defeat our enemies',
  'build a better world',
  'discover new knowledge',
  'promote justice',
  'create beauty',
  'inspire others',
  'expand our influence',
  'preserve our heritage',
  'innovate and improve',
  'empower our members',
  'cultivate strength',
  'foster collaboration',
  'establish peace',
  'exceed expectations',
  'honor our traditions',
  'unite under a common cause',
  'excel in all endeavors',
  'overcome adversity',
  'forge alliances',
  'nurture growth and development',
  'provide aid to those in need',
  'create a legacy',
  'spread enlightenment',
  'challenge the status quo',
  'protect the natural world',
  'uphold our values',
  'serve our community',
  'embrace diversity and inclusivity',
];
