import '../../../../generators/base/list_item_generator.dart';

class MonkeySpeciesGenerator extends ListItemGenerator<String> {
  static const _species = [
    'capuchin',
    'howler monkey',
    'squirrel monkey',
    'spider monkey',
    'woolly monkey',
    'tamarin',
    'marmoset',
    'saki monkey',
    'uakari',
    'night monkey',
    'titi monkey',
    'golden lion tamarin',
    'emperor tamarin',
    'cotton-top tamarin',
    'pygmy marmoset',
    'baboon',
    'macaque',
    'mandrill',
    'gelada',
    'colobus monkey',
    'langur',
    'proboscis monkey',
    'guenon',
    'patas monkey',
    'drill',
    'douc langur',
    'snub-nosed monkey',
    'leaf monkey',
    'siamang',
    'white-handed gibbon',
    'lar gibbon',
    'vervet monkey',
    'de brazza\'s monkey',
    'blue monkey',
    'red colobus',
    'black-and-white colobus',
    'grivet monkey',
    'olive baboon',
    'hamadryas baboon',
    'yellow baboon',
    'rhesus macaque',
    'barbary macaque',
    'pig-tailed macaque',
    'stump-tailed macaque',
    'crab-eating macaque',
    'gelada baboon',
    'golden snub-nosed monkey',
    'silvery lutung',
    'dusky leaf monkey',
    'purple-faced langur',
    'red-shanked douc',
    'black-shanked douc',
    'western red colobus',
    'mantled guereza',
    'dusky titi monkey',
    'bearded saki',
    'bald uakari',
    'golden-backed uakari',
    'kaapori capuchin',
    'black-faced lion tamarin',
    'blond capuchin',
  ];

  MonkeySpeciesGenerator() : super(_species);
}
