import '../../../../generators/base/list_item_generator.dart';

/// A class that generates traditions for tragedies
class TragedyTraditionGenerator extends ListItemGenerator<String> {
  static const _traditions = [
    'abstaining from food and drink for the day',
    'chanting laments under the darkened sky',
    'closing all windows and doors to symbolize isolation',
    'crafting effigies to represent the fallen',
    'dousing all lights to signify the lost hope',
    'fasting from sunrise to sunset in mourning',
    'gathering at grave sites to lay black flowers',
    'gathering in silence around the sacred flame',
    'lighting black candles in remembrance of the lost',
    'locking all doors to ward off evil spirits',
    'offering personal sacrifices at dawn',
    'painting faces with ash to symbolize grief',
    'placing stones at memorial sites',
    'planting trees to honor the fallen',
    'reciting elegies for the lost souls',
    'reciting the names of the deceased at twilight',
    'sending out messages of sorrow to the ancient ones',
    'shattering ceremonial pottery as a sign of despair',
    'singing dirges in low, mournful tones',
    'speaking to no one for the entire day',
    'staining garments with ash and earth',
    'standing vigil through the night in silence',
    'turning mirrors to the walls to avoid reflections',
    'walking barefoot through sacred grounds',
    'wearing black robes to symbolize mourning',
    'weaving wreaths of withered leaves',
    'writing messages of grief on paper and burning them',
    'abstaining from all forms of joy',
    'breaking bread but sharing with no one',
    'casting offerings into the sea for the lost',
    'covering mirrors and reflective surfaces',
    'destroying old possessions as a sign of loss',
    'fasting in solitude in memory of the lost ones',
    'gathering at dusk to whisper tales of the fallen',
    'laying wreaths of thorns at memorials',
    'lighting lanterns to guide lost spirits',
    'marching in solemn processions through the streets',
    'observing silence for an entire day',
    'offering a piece of clothing at memorials',
    'pouring libations into the earth to honor the dead',
    'pouring water onto the graves of loved ones',
    'praying in total silence for the lost souls',
    'reading the names of the deceased aloud',
    'refraining from speaking for a day',
    'sewing black patches onto garments',
    'shaving heads in ritual mourning',
    'shedding tears into a communal pool',
    'sitting in silence by the tombs of the fallen',
    'sprinkling ashes over sacred sites',
    'spreading salt on the earth to prevent growth',
    'standing with bowed heads at sunset',
    'tearing garments as a sign of grief',
    'turning off all lights until sunrise',
    'visiting ancestral graves to offer prayers',
    'wearing cloaks of dark colors to symbolize sorrow',
    'whispering names of the lost at sacred places',
    'writing the names of the deceased on stones',
    'burning symbolic items as offerings to the lost',
    'covering heads with cloth as a sign of grief',
    'destroying personal items as an act of remembrance',
    'fasting for the lost souls at dawn',
    'gathering at memorials to share stories of the dead',
    'laying wreaths of black flowers at the memorial',
    'lighting torches to ward off the spirits of the lost',
    'marching through the streets in silence',
    'offering symbolic gifts to the spirits',
    'performing solemn dances of grief',
    'placing candles on graves',
    'placing offerings of food for the spirits of the lost',
    'reciting prayers for the fallen at dusk',
    'shutting down businesses for a day of mourning',
    'singing songs of grief in the streets',
    'speaking only in whispers throughout the day',
    'sprinkling holy water over gravesites',
    'standing in silence by the graves of the fallen',
    'tearing ribbons of black cloth as a symbol of grief',
    'turning away from the rising sun in sorrow',
    'wearing clothing of dark fabric as a sign of mourning',
    'weaving tapestries of sorrow for the lost',
    'writing names of the fallen on parchment and burning it',
    'extinguishing fires as a sign of respect for the lost',
    'carrying black banners through the streets',
    'draping black cloth over statues in the city',
    'walking barefoot in remembrance of the fallen',
    'wearing veils to symbolize the mourning of the lost',
    'writing lamentations on stones and casting them into the sea',
    'offering a moment of silence at every hour',
    'planting flowers of grief at sacred sites',
    'whispering prayers into the wind for the lost',
    'covering the streets with ashes as a sign of mourning',
    'placing symbols of loss on altars throughout the day',
    'observing moments of silence at dusk and dawn',
    'destroying tokens of past joy as a sign of grief',
    'offering songs of mourning at sacred sites',
    'reciting poems of sorrow by the graves of the fallen'
  ];

  TragedyTraditionGenerator() : super(_traditions);
}
