import '../../../../generators/base/list_item_generator.dart';

/// A class that generates specialties of a mage guilds
class MagesSpecialtyGenerator extends ListItemGenerator<String> {
  static const _specialties = [
    'divination and prophecy services',
    'time magic and chronomancy',
    'weather manipulation and control',
    'teleportation and portal magic',
    'elemental magic, specializing in a specific element',
    'necromancy and communicating with the dead',
    'shadow magic and illusion',
    'mind reading and control',
    'barrier magic and protection spells',
    'shapeshifting and polymorphing',
    'light magic and illumination spells',
    'dimensional magic and planar travel',
    'curse breaking and dispelling',
    'warding and protection against evil magic',
    "dream magic and entering other's dreams",
    'energy manipulation and harnessing',
    'animal magic and communication with beasts',
    'healing and restorative magic',
    'enchantment and charm spells',
    'magical item repair and restoration',
    'soul magic and soul trapping',
    'elemental summoning and binding',
    'gravity magic and control',
    'earth magic and manipulation',
    'flight and levitation spells',
    'song magic and musical enchantments',
    'illusion and glamour spells',
    'transformation and transmutation',
    'illness and disease control and eradication',
    'detection and sensing spells',
    'fire magic and control',
    'protection and shielding spells',
    'light manipulation and shadow magic',
    'body modification and enhancement spells',
    'time manipulation and time travel',
    'foresight and precognition',
    'invisibility and stealth spells',
    'blood magic and life force manipulation',
    'plant magic and communication with plants',
    'space magic and void manipulation',
    'force magic and telekinesis',
    'sound manipulation and control',
    'technomancy and control of machines and technology',
    'water magic and control',
    'magnetic manipulation and control',
    'chaos magic and unpredictability',
    'illness and disease creation and infliction',
    'poison and venom creation and manipulation',
    'ice magic and control',
    'divine magic and connection to deities',
  ];

  MagesSpecialtyGenerator() : super(_specialties);
}
