import '../../../../generators/base/list_item_generator.dart';

/// A class that generates traditions for celebrations
class CelebrationTraditionGenerator extends ListItemGenerator<String> {
  static const _traditions = [
    "lighting festive lanterns",
    "singing joyful songs",
    "decorating with colorful banners",
    "sharing delicious meals",
    "exchanging gifts",
    "holding parades",
    "dancing in the streets",
    "creating handmade decorations",
    "performing traditional dances",
    "baking special treats",
    "gathering with family and friends",
    "telling stories from the past",
    "hosting community feasts",
    "participating in friendly games",
    "wearing traditional clothing",
    "sending greeting cards",
    "building altars of thanks",
    "organizing talent shows",
    "displaying colorful fireworks",
    "planting trees or flowers",
    "lighting candles",
    "reciting poetry",
    "making and sharing crafts",
    "visiting local attractions",
    "organizing scavenger hunts",
    "enjoying outdoor picnics",
    "creating and sharing art",
    "making flower crowns",
    "donating to charity",
    "holding storytelling sessions",
    "writing messages of hope",
    "participating in charity runs",
    "playing musical instruments",
    "having a community bonfire",
    "inviting neighbors to celebrate",
    "creating gratitude jars",
    "hosting game nights",
    "baking and sharing bread",
    "dressing up in costumes",
    "sending blessings to loved ones",
    "sharing favorite recipes",
    "making wishes and hopes",
    "holding community workshops",
    "engaging in friendly competitions",
    "crafting seasonal wreaths",
    "organizing sports tournaments",
    "singing carols",
    "sending messages to the heavens",
    "offering thanks to nature",
    "celebrating with storytelling circles",
    "honoring ancestors",
    "creating and displaying art",
    "organizing themed movie nights",
    "offering prayers for peace",
    "joining in meditation sessions",
    "waving flags and banners",
    "sharing joy with the less fortunate",
    "creating seasonal traditions",
    "sending blessings via social media",
    "crafting tokens of appreciation",
    "holding a holiday market",
    "wearing matching outfits",
    "engaging in community service",
    "creating and sharing playlists",
    "planting herbs for prosperity",
    "taking family portraits",
    "sharing memories in a scrapbook",
    "creating shadow puppets",
    "drawing inspiration from nature",
    "sending out festive invitations",
    "creating a holiday countdown",
    "planting a community garden",
    "making ornaments for trees",
    "offering blessings in public",
    "crafting handmade gifts",
    "sharing light with neighbors",
    "exploring local nature trails",
    "using natural materials for crafts",
    "making resolutions for the future",
    "celebrating with tea or coffee",
    "organizing food drives",
    "spreading kindness through notes",
    "inviting elders to share wisdom",
    "lighting sparklers at night",
    "holding storytelling contests",
    "creating communal murals",
    "sharing inspirational quotes",
    "practicing yoga together",
    "gathering in circles to share",
    "hosting seasonal fairs",
    "creating seasonal photo booths",
    "watching the sunrise together",
    "writing down hopes for the future",
    "inviting musicians to perform",
    "sending postcards to loved ones",
    "creating a community time capsule",
    "honoring local wildlife",
    "sharing tales of adventure",
    "making handmade jewelry",
    "organizing hiking trips",
    "setting up mini-golf courses",
    "crafting holiday-themed puzzles",
    "creating and displaying quilts",
    "making dream catchers",
    "organizing dance-offs",
    "gathering for storytelling nights",
    "spreading joy with flower seeds",
    "making kites for fun",
    "having water balloon fights",
    "building and decorating gingerbread houses",
    "playing board games together",
    "creating a community cookbook",
    "collecting and sharing memories",
    "planting flowers in the community",
    "celebrating with a fashion show",
    "creating art installations",
    "crafting scrapbooks together",
    "organizing themed potlucks",
    "building forts for fun",
    "creating seasonal recipes",
    "sharing cultural traditions",
    "having outdoor movie nights",
    "planting a tree for each family member",
    "creating seasonal playlists",
    "visiting historical sites",
    "crafting seasonal bookmarks",
    "spreading positivity through art",
    "hosting talent shows",
    "engaging in storytelling sessions",
    "watching cultural performances",
    "creating seasonal flower arrangements",
    "making personalized gifts",
    "organizing outdoor games",
    "sharing seasonal scents",
    "engaging in community discussions",
    "sending handwritten letters",
    "organizing game tournaments",
    "creating festive table settings",
    "holding trivia nights",
    "taking neighborhood walks",
    "offering help to neighbors",
    "hosting potluck dinners",
    "writing letters to future generations",
    "having a community art day",
    "decorating community spaces",
    "hosting karaoke nights",
    "crafting gratitude banners",
    "making memory stones",
    "creating vision boards",
    "offering free hugs",
    "having storytelling nights",
    "hosting cultural exchange events",
    "creating collaborative artworks",
    "making handmade soaps",
    "gathering for bonfire nights",
    "watching cultural films",
    "engaging in community debates",
    "organizing community sports",
    "celebrating with seasonal dances",
    "crafting DIY projects together",
    "having open mic nights",
    "holding themed art exhibits",
    "organizing group excursions",
    "celebrating with community parades",
    "decorating community centers",
    "sharing secret gifts",
    "crafting personalized greeting cards",
    "making snowmen or sandcastles",
    "having friendly competitions",
    "writing down wishes on paper lanterns",
    "gathering for themed potluck lunches",
    "celebrating milestones together",
    "inviting local artists to share their work",
    "organizing community clean-up days",
    "celebrating with laughter and joy",
    "making and sharing fruit preserves",
    "participating in seasonal festivals",
    "sending messages in bottles",
    "crafting dream journals",
    "having neighborhood brunches",
    "organizing charity drives",
    "creating friendship bracelets",
    "creating holiday-themed playlists",
    "offering free workshops",
    "sharing favorite memories",
    "building community with open hearts",
    "making holiday cards for the community",
    "hosting themed costume parties",
    "creating community art projects",
    "organizing holiday challenges",
    "celebrating with love and laughter",
    "sharing homemade meals",
    "planting wildflower seeds",
    "organizing reading groups",
    "engaging in group activities",
    "hosting holiday dinners",
    "creating seasonal dioramas",
    "organizing singing circles",
    "crafting decorative bookmarks",
    "celebrating with cultural foods",
    "holding community festivals",
    "creating holiday-themed poems",
    "inviting everyone to participate",
    "making and sharing herbal teas",
    "having themed scavenger hunts",
    "offering help to those in need",
    "planting a community orchard",
    "making bird feeders",
    "holding group outings",
    "creating a community library",
    "honoring local heroes",
    "gathering to share experiences",
    "celebrating with kindness and compassion",
    "crafting flower arrangements",
    "creating a gratitude wall",
    "inviting musicians to play",
    "creating seasonal journals",
    "participating in themed workshops",
    "sharing food from different cultures",
    "gathering for community coffee",
    "creating seasonal rituals",
    "organizing dance parties",
    "celebrating with artistic expression",
    "inviting storytellers to share tales",
    "engaging in group mindfulness",
    "celebrating through laughter",
    "hosting potluck brunches",
    "making nature-inspired crafts",
    "gathering for garden parties",
    "crafting seasonal decorations",
    "having themed game nights",
    "creating and sharing poetry",
    "organizing community dinners",
    "celebrating with open hearts",
    "spreading love through actions",
    "creating vision boards together",
    "holding friendship picnics",
    "having outdoor adventures",
    "creating community connections",
    "celebrating through giving",
    "sharing favorite stories",
    "making and sharing pies",
    "creating a holiday spirit",
    "holding craft fairs",
    "organizing holiday concerts",
    "creating seasonal playlists together",
    "sharing family traditions",
    "crafting homemade treats",
    "inviting neighbors for coffee",
    "participating in local events",
    "making nature crafts together",
    "building community through sharing",
    "celebrating life together",
  ];

  CelebrationTraditionGenerator() : super(_traditions);
}
