import '../../../../generators/base/list_item_generator.dart';

/// A class that generates traditions for celebrations
class CelebrationTraditionGenerator extends ListItemGenerator<String> {
  static const _traditions = [
    'baking bread blessed by the earth spirits',
    'baking magical pastries',
    'building altars to honor the deities',
    'building and decorating gingerbread cottages',
    'building community through shared experiences',
    'celebrating life with joy and wonder',
    'celebrating life with laughter and magic',
    'celebrating milestones in grand style',
    'celebrating with a costume ball',
    'celebrating with a grand masquerade ball',
    'celebrating with kindness and good cheer',
    'celebrating with laughter and camaraderie',
    'celebrating with storytelling circles of bards',
    'collecting and sharing legendary tales',
    'crafting dream catchers with magical threads',
    'crafting enchanted decorations for homes',
    'crafting handmade gifts of wonder',
    'crafting handmade greeting cards with enchantments',
    'crafting handmade talismans',
    'crafting homemade potions and elixirs',
    'crafting magical flower arrangements',
    'crafting seasonal bookmarks with runes',
    'crafting seasonal wreaths of twigs and flowers',
    'crafting tokens of appreciation with magic',
    'creating a community altar to honor the spirits',
    'creating a community grimoire of recipes',
    'creating a community time capsule of memories',
    'creating a gratitude wall with offerings',
    'creating a holiday countdown with charms',
    'creating a holiday spirit with joy and laughter',
    'creating and displaying magical art',
    'creating and sharing art with runes',
    'creating and sharing magical playlists',
    'creating art installations of mythical beings',
    'creating community with a festival of colors',
    'creating friendship charms for the community',
    'creating gratitude stones with runes',
    'creating seasonal flower arrangements with rare blooms',
    'creating seasonal journals filled with magic',
    'creating seasonal legends in story form',
    'creating seasonal playlists of enchanting melodies',
    'creating seasonal rituals to honor the earth',
    'creating shadow puppets with light magic',
    'dancing under the moonlight',
    'decorating local landmarks with magical symbols',
    'decorating with mystical banners',
    'displaying fireworks that paint the sky',
    'donating to local charities of the realm',
    'drawing inspiration from mythical creatures',
    'dressing in costumes of legendary figures',
    'engaging in community service for the needy',
    'engaging in friendly competitions of skill',
    'engaging in storytelling sessions with the elders',
    'enjoying outdoor picnics in enchanted groves',
    'exchanging enchanted gifts',
    'exploring local enchanted landmarks',
    'gathering around the hearth with family',
    'gathering for community bonfires',
    'gathering for enchanted tea ceremonies',
    'gathering for storytelling nights by the fire',
    'gathering for themed potluck lunches',
    'gathering to share experiences of the journey',
    'having friendly archery contests',
    'having friendly races through the forest',
    'having open mic nights for bards and poets',
    'having themed feasts with mythical flavors',
    'holding a mystical market day',
    'holding craft fairs for magical goods',
    'holding grand parades of creatures',
    'holding storytelling contests by the fire',
    'holding themed art exhibits of mythical scenes',
    'holding trivia nights about legendary lore',
    'holding workshops for magical crafts',
    'honoring the balance of nature and magic',
    'honoring the spirits of ancestors',
    'hosting community events for all creatures',
    'hosting feasts in the great hall',
    'hosting game nights with magical board games',
    'hosting talent shows of magical feats',
    'inviting local artisans to showcase their work',
    'inviting local musicians to play under the stars',
    'inviting local storytellers to share their wisdom',
    'inviting neighbors for magical tea parties',
    'inviting neighbors to celebrate with joy',
    'joining in meditative rituals under the stars',
    'lighting candles of various hues',
    'lighting enchanted lanterns',
    'making and sharing enchanted crafts',
    'making and sharing herbal concoctions',
    'making and sharing sweet confections',
    'making flower crowns of rare blooms',
    'making kites that soar with enchantment',
    'making nature-inspired crafts from local resources',
    'making ornaments for enchanted trees',
    'making personalized charms for friends',
    'making seasonal traditions unique to families',
    'making snowmen or sandcastles with magic',
    'making wishes and hopes under the stars',
    'offering blessings in public gatherings',
    'offering help to those in magical need',
    'offering prayers for peace in the realm',
    'offering thanks to the guardians of the land',
    'organizing community clean-up days with purpose',
    'organizing dance-offs in the village square',
    'organizing friendly competitions of strength',
    'organizing group excursions to magical places',
    'organizing holiday concerts in the town square',
    'organizing jousts and friendly duels',
    'organizing magical scavenger hunts',
    'organizing outdoor adventures in mystical lands',
    'organizing talent showcases of spells',
    'organizing themed festivals of the seasons',
    'participating in charity races through the town',
    'participating in friendly tournaments',
    'participating in local magical events',
    'participating in themed workshops for spells',
    'performing traditional folk dances',
    'planting a community garden of magical herbs',
    'planting flowers that bloom only on special nights',
    'planting herbs known for their powers',
    'planting sacred herbs for prosperity',
    'playing card games with magical elements',
    'playing musical instruments of elven design',
    'reciting epic poetry',
    'sending blessings through enchanted scrolls',
    'sending blessings to the forest and seas',
    'sending messages to the spirits of nature',
    'sending messages via enchanted birds',
    'sending out festive invitations on parchment',
    'sending wishes to the stars in song',
    'sharing family traditions passed down through time',
    'sharing feasts of exotic dishes',
    'sharing foods from different cultures of the realm',
    'sharing joy with those less fortunate',
    'sharing light with neighbors through lanterns',
    'sharing memories in a scroll of tales',
    'sharing secret gifts of kindness',
    'sharing secret recipes passed through generations',
    'singing ancient ballads',
    'singing carols that tell ancient tales',
    'spreading joy with flower seeds of luck',
    'spreading positivity through enchanted art',
    'taking family portraits in enchanted forests',
    "taking neighborhood walks in nature's embrace",
    'telling tales of legendary heroes',
    'visiting ancient ruins for inspiration',
    'watching performances by magical creatures',
    'waving colorful flags and banners in the breeze',
    'wearing garments of colorful fabric',
    'wearing matching robes of festive colors',
    'writing wishes on enchanted lanterns',
    'writing wishes on parchment and burning them'
  ];

  CelebrationTraditionGenerator() : super(_traditions);
}
