import '../../../../generators/base/list_item_generator.dart';

/// A class that generates specialties of an cults
class CultSpecialtyGenerator extends ListItemGenerator<String> {
  static const _specialties = [
    'dealing in illicit substances and drugs',
    'performing dark and forbidden rituals to gain power',
    'brainwashing and manipulating new recruits',
    'engaging in human sacrifice to appease their deity',
    'practicing necromancy and raising the dead',
    'stealing artifacts and relics from other religions and cultures',
    'preaching hatred and intolerance towards other religions and races',
    'conducting secret and illegal experiments on living beings',
    'profiting off the suffering of others',
    'smuggling contraband goods and weapons',
    'providing assassination services for a price',
    'engaging in cannibalism as part of their rituals',
    'conspiring against governments and political figures',
    'exploiting vulnerable populations for their own gain',
    'operating a network of spies and informants',
    'enforcing strict and oppressive rules on their members',
    'infiltrating and manipulating other organizations and groups',
    'using mind control to maintain obedience and loyalty',
    'practicing blood magic to gain power and influence',
    'cultivating a culture of fear and paranoia within their ranks',
    'preparing for a violent and apocalyptic event',
    'engaging in acts of terrorism and sabotage',
    'creating and selling dangerous and illegal drugs',
    'practicing dark and dangerous forms of magic',
    'taking part in illegal human trafficking',
    'spreading false information and propaganda to gain support',
    'using blackmail and extortion to manipulate others',
    'training assassins and mercenaries to carry out their bidding',
    'practicing the dark art of demon summoning',
    'engaging in acts of piracy and robbery on the high seas',
    'using their influence to corrupt officials and government institutions',
    'practicing bloodletting and self-harm as part of their rituals',
    'kidnapping and holding people for ransom',
    'creating and selling cursed and dangerous artifacts',
    'using their magic to control the weather and cause natural disasters',
    'operating a shadowy and illegal slave trade',
    'conspiring with other cults and dark organizations for mutual gain',
    'developing and deploying deadly poisons and toxins',
    'using their magic to summon and control dangerous monsters',
    'conducting illegal and unethical medical experiments',
    'sacrificing animals as part of their rituals',
    'preaching radical and extremist political ideologies',
    'engaging in the black market trade of rare and illegal items',
    'practicing body modification and mutilation as part of their rituals',
    'creating and selling cursed and haunted real estate',
    'exploiting the supernatural abilities of children for their own gain',
    'engaging in human organ trafficking',
    'practicing the art of soul binding and enslavement',
    'infiltrating and corrupting legitimate religions and spiritual practices',
  ];

  CultSpecialtyGenerator() : super(_specialties);
}
