import '../../../../generators/base/list_item_generator.dart';

/// A class that generates origin for tragedies
class TragedyOriginGenerator extends ListItemGenerator<String> {
  static const _origins = [
    'a betrayal by trusted allies',
    'a cataclysmic storm that shattered the land',
    'a cursed bloodline doomed to suffer',
    'a deadly famine that swept across the lands',
    'a forbidden love that ended in ruin',
    'a forgotten oath broken by the ancestors',
    'a great fire that consumed the capital',
    'a great flood that drowned an entire kingdom',
    'a king who led his people into despair',
    'a lost battle that ended a golden age',
    'a massive earthquake that split the earth',
    'a plague that wiped out a generation',
    'a rebellion that was brutally crushed',
    'a river of blood from fallen warriors',
    'a sea voyage that ended in death',
    'a shadow that fell over the hearts of men',
    'a time of endless drought',
    'an ancient curse brought upon by greed',
    'an apocalyptic war between nations',
    'an empire that collapsed under its own weight',
    'an eternal winter that froze the lands',
    'an execution of an innocent queen',
    'an unholy alliance with dark forces',
    'the awakening of a sleeping terror',
    'the banishment of a hero who could not return',
    'the blackening of the sun for an entire year',
    'the blight that withered crops and hopes',
    'the breaking of the sacred bond',
    'the collapse of the greatest city',
    'the cruel reign of a mad king',
    'the curse of the weeping mountains',
    'the disappearance of a generation of children',
    'the fall of the last golden city',
    'the fall of the proudest empire',
    'the forgotten massacre at dawn',
    'the massacre of a royal family',
    'the mourning of a thousand souls',
    'the murder of the last rightful heir',
    'the night the stars disappeared',
    'the night the waters ran red with blood',
    'the return of an ancient evil',
    'the rise of the blood moon',
    'the shattered pact of peace',
    'the siege that lasted a century',
    'the sinking of an island kingdom',
    'the slaying of the sacred beast',
    'the storms that never ceased',
    'the summoning of forbidden powers',
    'the tearing of the earth asunder',
    'the theft of the sacred relic',
    'the vanishing of the chosen one',
    'the war that consumed all nations',
    'the wrath of the vengeful gods',
    'the day the mountains crumbled',
    'the day the seas boiled',
    'the day the skies wept fire',
    'the death of the last hero',
    'the exile of the wise ones',
    'the fall of the great wall',
    'the fall of the hero into madness',
    'the forgotten slaughter of innocents',
    'the forsaking of the ancient gods',
    'the great exile of the people',
    'the great famine that emptied cities',
    'the great flood that destroyed the plains',
    'the great migration of the lost tribes',
    'the loss of the sacred text',
    'the mourning of the nameless dead',
    'the reign of terror under the tyrant',
    'the rise of the warlords',
    'the river that carried away hope',
    'the sacrifice of the chosen child',
    'the scourge of the endless plague',
    'the slaying of the high priestess',
    'the tragedy of the unholy pact',
    'the unending war of the brothers',
    'the vanishing of the sacred grove',
    'the vengeance of the ancient spirits',
    'the war that left nothing but ashes',
    'the wailing of the cursed lands',
    'the whispering shadows of the lost',
    'the withering of the sacred tree',
    'the year of endless sorrow',
    'the year the crops failed',
    'the day the moon shattered',
    'the ruin of the last kingdom',
    'the betrayal of the firstborn',
    'the day the wolves returned',
    'the culling of the innocent',
    'the burning of the sacred forest',
    'the forsaking of the ancient code',
    'the sinking of the temple of light',
    'the banishment of the sun gods',
    'the breaking of the great chain',
    'the massacre of the last tribe',
    'the wailing of the forgotten ones'
  ];

  TragedyOriginGenerator() : super(_origins);
}
