import '../../../../generators/base/list_item_generator.dart';

/// A class that generates specialties of a knight orders
class KnightsSpecialtyGenerator extends ListItemGenerator<String> {
  static const _specialties = [
    'siege warfare',
    'siege defense',
    'naval warfare',
    'mountain climbing and warfare',
    'cavalry charges',
    'archery',
    'sword fighting',
    'jousting',
    'chivalry and honor',
    'strategy and tactics',
    'intelligence analysis',
    'battlefield medicine',
    'torture and interrogation',
    'assassination by magic',
    'necromancy',
    'divination',
    'enchantment and mind control',
    'demon summoning and banishment',
    'elemental magic',
    'healing magic',
    'illusion magic',
    'teleportation',
    'time magic',
    'telekinesis',
    'geomancy and earth magic',
    'light magic',
    'dark magic',
    'blood magic',
    'summoning and controlling animals',
    'summoning and controlling monsters',
    'summoning and controlling spirits',
    'shape-shifting',
    'flight and levitation',
    'invisibility',
    'telepathy and mind reading',
    'elemental resistance',
    'magic immunity',
    'tracking and hunting monsters',
    'disarming traps and alarms',
    'siege weaponry construction',
    'armor crafting',
    'weapon crafting',
    'horse breeding and training',
    'animal husbandry',
    'diplomacy and negotiation',
    'heraldry and symbolism',
    'religious devotion and piety',
  ];

  KnightsSpecialtyGenerator() : super(_specialties);
}
