import '../../../../generators/base/list_item_generator.dart';

/// A class that generates quests for knight orders
class KnightsQuestGenerator extends ListItemGenerator<String> {
  static const _quests = [
    'investigate reports of a powerful artifact that could be of interest to the order',
    'escort a group of refugees through dangerous territory to a safe haven',
    'train a group of local soldiers in advanced combat techniques to defend their village',
    'infiltrate a rival faction to gather information on their activities and plans',
    'retrieve a powerful relic from a dangerous dungeon or tomb',
    'help a besieged city or town repel an invasion by a hostile force',
    'investigate a series of disappearances in a remote town or village',
    'hunt down and eliminate a group of dangerous bandits who are terrorizing the countryside',
    'rescue a group of kidnapped nobles who have been taken by a rival faction',
    'investigate a dark cult that is rumored to be performing human sacrifices',
    'deliver a valuable message to a distant ally or important figure',
    "sabotage a rival faction's trading operation to weaken their position",
    'help a group of farmers defend their land against marauding monsters or raiders',
    'investigate a series of murders in a major city that may be connected to a larger conspiracy',
    'defend a valuable caravan of supplies from a band of raiders or monsters',
    'negotiate a peace treaty or truce between warring factions',
    'discover the source of a mysterious plague that is spreading throughout the land',
    'rescue a kidnapped princess or important figure from a dangerous stronghold',
    'hunt down and slay a powerful monster that is threatening a town or village',
    'establish a new outpost or stronghold in a strategic location',
    'investigate a dark wizard who is rumored to be conducting dangerous experiments',
    'help a group of refugees establish a new home in a safe location',
    'defend a vital trade route from attacks by bandits or monsters',
    'uncover a conspiracy to overthrow a local ruler or noble',
    'recover a lost or stolen artifact that is of great importance to the order',
    'secure a valuable alliance with a powerful local ruler or noble',
    'investigate a mysterious disappearance at a remote monastery or temple',
    'negotiate a favorable treaty or trade agreement with a foreign power',
    'rescue a group of miners who have been trapped in a collapsed mine',
    'hunt down and eliminate a dangerous assassin who is targeting important figures',
    'defend a major city or fortress from a large-scale siege or invasion',
    'investigate a series of strange occurrences or omens that are causing fear and panic among the populace',
    'establish a new trade route or partnership with a foreign merchant house',
    'recover a powerful magical artifact that has been lost for centuries',
    'help a group of rebels overthrow a tyrannical ruler or government',
    'investigate a mysterious portal or gate that has suddenly appeared in the land',
    'deliver a vital shipment of supplies to a besieged city or fortress',
    'defend a valuable strategic location from a rival faction or foreign invader',
    'uncover a plot to assassinate an important figure or ruler',
    'rescue a group of prisoners who have been taken by a dangerous faction',
    'investigate a series of thefts or burglaries that may be connected to a larger conspiracy',
    'recover a lost or stolen treasure that is of great importance to the order',
    'help a group of farmers defend their crops from a swarm of locusts or other pests',
    'defend a group of travelers or pilgrims from attacks by monsters or bandits',
    'investigate a powerful sorcerer who is rumored to be threatening the local populace',
    'deliver a powerful weapon or artifact to a distant ally or stronghold',
  ];

  KnightsQuestGenerator() : super(_quests);
}
