import '../../../../generators/base/list_item_generator.dart';

/// A class that generates quests for druid circles
class DruidsQuestGenerator extends ListItemGenerator<String> {
  static const _quests = [
    "cleanse a corrupted forest from a curse that's been causing it to wither",
    "investigate the disappearance of a valuable artifact that was under the circle's protection",
    "help a nearby village solve a mysterious illness that's been plaguing their crops and livestock",
    'travel to a distant land to retrieve a rare seed that can only be found there to revitalize the soil',
    'guide a group of settlers through an untamed wilderness to establish a new settlement',
    'assist a local lord with a pest problem that has been destroying his crops',
    'investigate a dark presence that has been corrupting the animals of the forest and driving them to attack travelers',
    'retrieve a lost artifact that has been stolen by a rival druid circle',
    'help a wounded unicorn that has been attacked by a group of hunters and is in danger of dying',
    'investigate a group of hunters who have been poaching endangered animals and selling them on the black market',
    'help a sick child who has been cursed by an evil witch',
    'protect a rare and endangered species from a group of poachers who have been hunting them for their valuable hides',
    "investigate a mysterious illness that has been spreading among the circle's members",
    "defend the circle's sacred grove from an invading army",
    'help a neighboring kingdom with a drought by summoning rain',
    "retrieve a sacred relic that has been stolen from the circle's altar",
    'find and rescue a group of travelers who have been lost in the forest and are in danger of being attacked by dangerous creatures',
    "investigate a strange portal that has appeared in the circle's territory, which seems to lead to another world",
    'help a nearby village deal with a band of goblins that has been raiding their farms and homes',
    'travel to a distant land to learn new magic that can help the circle better protect the forest',
    'defend a nearby town from a group of raiders who have been pillaging and burning everything in their path',
    'help a group of refugees who have been displaced by a war and are in need of shelter and protection',
    "investigate a strange blight that has been killing the circle's sacred trees",
    'find and stop a group of necromancers who have been raising the dead and unleashing them upon the living',
    'help a young druid who has been struggling to master her powers',
    "retrieve a valuable ingredient for a powerful potion that can cure a deadly disease that's been plaguing the region",
    'investigate a strange fog that has been enveloping the forest and causing travelers to get lost',
    'find and stop a group of rogue druids who have been using their powers for evil',
    'help a group of dryads who have been attacked by loggers and are in danger of losing their homes',
    'investigate a group of bandits who have been attacking caravans and merchants traveling through the forest',
    'retrieve a lost artifact that has been hidden in a dangerous dungeon',
    "help a group of farmers who have been struggling with a blight that's been killing their crops",
    'investigate a strange creature that has been terrorizing a nearby village',
    'retrieve a rare flower that blooms only once a year and is needed for a powerful ritual',
    'help a group of refugees who have been driven from their homes by a dragon that has been attacking their village',
    'investigate a group of cultists who have been performing dark rituals in the forest',
    "retrieve a stolen magical staff that belongs to the circle's leader",
    "help a nearby kingdom deal with a plague that's been spreading through their cities",
    'investigate a mysterious illness that is affecting the crops and livestock in a nearby village, and find a way to cure it before it spreads further',
    'protect a sacred grove from a group of loggers who are attempting to clear the land for profit',
    'locate and retrieve a powerful magical artifact that has been hidden in a dangerous and inhospitable wilderness',
    'help a group of settlers establish a new colony in a remote and challenging location by providing advice and assistance with survival skills',
    'investigate a series of strange disappearances in a nearby forest, and determine whether they are the result of natural causes or something more sinister',
    'assist a group of druidic allies in a neighboring region who are struggling against a powerful and corrupt mage',
    'find and negotiate with a reclusive hermit who possesses knowledge of a rare and valuable herb that can only be found in a treacherous and remote location',
    'prevent a powerful industrialist from building a factory in a pristine wilderness area, which would have devastating consequences for the local ecosystem',
    'help a group of indigenous people protect their ancestral lands from an encroaching army of settlers who are looking to expand their territory',
    'locate and protect a group of rare and endangered creatures that are in danger of being hunted to extinction by unscrupulous poachers',
  ];

  DruidsQuestGenerator() : super(_quests);
}
