import '../../../../generators/base/list_item_generator.dart';

/// A class that generates forest features
class ForestFeatureGenerator extends ListItemGenerator<String> {
  static const _features = [
    "has enchanted trees",
    "has glowing mushrooms",
    "has fairy cycles",
    "has color-changing leaves",
    "has color-changing barks",
    "has numerous magical ruins",
    "has numerous abandoned shacks",
    "has endemic creatures",
    "has sounds from an unknown source",
    "has poisonous plants",
    "has a secret organization",
    "has abandoned tree-houses",
    "has glowing stones",
    "has cursed area",
    "has moving trees",
    "has a tree that has grown so large that it supports an entire ecosystem on its branches, including its own soil and water sources",
    "is always in a state of dusk or twilight",
    "has underground caves and tunnels",
    "has spirits that takes a form of animals",
    "has shifting paths",
    "has hidden waterfall with magical capabilities",
    "has exceptionally tall trees",
    "is covered by moss",
    "has trees with twisted trunks",
    "has small streams of water",
    "has leafless trees",
    "has trees that glow softly in the dark",
    "is dense and shadowy, is shrouded in darkness, with little light penetrating through the thick canopy of trees",
    "has twisted, gnarled trees with red sap that seems to drip like blood from the bark",
    "has grown wild and untamed, with thorns and brambles covering the forest floor and vines twisting around tree trunks",
    "has trees which seem to sing with the breeze, and the air is filled with a soft, haunting melody",
    "has trees which are alive and imbued with elemental magic, and the creatures that dwell within are closely connected to nature",
    "has trees which seem to whisper secrets to those who wander beneath their boughs, and the air is always filled with a soft, eerie rustling",
    "is a forest that seems to shift and move on its own, with trees that twist and turn like living things and paths that seem to lead in circles",
    'has a grove of trees that bear fruit with magical properties',
    'has a hidden glade where ancient druids still practice their magic',
    'has a tree that has grown in the shape of a spiral staircase, leading up to a platform with a view of the entire forest',
    'has a section of the forest that is haunted by the ghosts of former inhabitants',
    'has a tree with leaves that emit a soothing, calming scent when touched',
    'has a section of the forest that is protected by a group of guardians who will only allow those with pure intentions to enter',
    'has a network of interconnected tree roots that form natural bridges and pathways through the forest',
    'has a grove of trees that bloom with beautiful, but deadly flowers',
    'has a section of the forest that is perpetually covered in mist, with strange, ethereal creatures lurking within',
    'has a hidden grove where a rare species of magical creature resides, only appearing to those who are worthy of their presence',
    'has a group of trees that appear to be melting or bending in unusual ways',
    'has a section of the forest where the trees grow in perfect symmetry, creating an otherworldly, almost artificial appearance',
    'has a tree that is said to grant wishes to those who make an offering at its base'
  ];

  ForestFeatureGenerator() : super(_features);
}
