const genericPersonalityQuirks = [
  'has a constant wanderlust and is unable to live at the same place for more than a few months',
  "doesn't like change.",
  'frequently quotes proverbs',
  'frequently misquotes proverbs',
  'falls in and out of love easily',
  'believes in soulmates',
  'is always joking, even at inappropriate times',
  'has a joke for every situation',
  "doesn't like listening to jokes.",
  'is constantly flattering people',
  'is a compulsive gambler',
  'is an alcoholic',
  'frequently lies',
  'believes in whatever deity is most helpful at a given moment',
  'is kleptomaniac',
  'always does what told not to',
  'gets very mad at any semblance of an insult',
  'has a story for everything',
  'sees insults as an art',
  'is a cross-dresser',
  'runs everywhere instead of walking',
  'dreams of becoming rich and famous',
  'admires the local lord',
  'knows all the gossip around town',
  'is always sharing wisdom',
  'believes in destiny',
  'argues about everything',
  'spaces out often, lost in thought',
  'makes anyone in a conversation with to feel like the most important person in the world',
  'cares about friends and will do anything for them',
  'reads any available book',
  'loves discovering new mysteries and solving them',
  'wants to know every side of a story before expressing an opinion',
  'is slightly paranoid',
  'works hard to play hard afterwards',
  'stretches the truth to tell a good story',
  'is haunted by horrible memories',
  'has lost many friends',
  'has a crude sense of humour',
  'likes finding direct solutions to problems',
  'always carries food in the pockets',
  'frequently asks questions',
  'is a local sport champion',
  'frequently laughs at inappropriate times',
  'believes that dwarves are planning to destroy the world',
  'believes that orcs are planning to destroy the world',
  'believes that elves are planning to destroy the world',
  'believes that tieflings are planning to destroy the world',
  'goes out at night secretly looking for weapons',
  'owns a box full of dead animals',
  'sets up local dance clubs',
  'lies poorly on purpose',
  'collects cute rocks',
  'collects sea shells',
  'collects tiny animal skulls',
  'secretly wants to become the ruler of the city',
  'has a dragon hatchling companion',
  'has a pigeon companion',
  'has a mouse companion',
  'has a fox companion',
  'has a parrot companion',
  'likes to swim',
  'has a beautiful singing voice',
  'frequently thinks aloud'
];
