import '../../../../generators/base/list_item_generator.dart';

/// A class that generates activities that dogs often do
class DogActivityGenerator extends ListItemGenerator<String> {
  static const _activities = [
    'play fetch',
    'chase other animals',
    'explore new scents',
    'snuggle up',
    'greet strangers',
    'learn new tricks',
    'run',
    'bark at intruders',
    'give kisses',
    'dig',
    'herd livestock',
    'guard the home',
    'track scents',
    'go for walks',
    'swim',
    'snooze in the sun',
    'keep watch',
    'chew on bones',
    'play with other dogs',
    'roll in the grass',
    'patrol the neighborhood',
    'guard the yard',
    'fetch sticks',
    'sniff around',
    'explore the backyard',
    'chase butterflies',
    'nap in the shade',
    'play tug-of-war',
    'greet with a lick',
    'roll in the mud',
    'wait by the door',
    'chase birds',
    'learn obedience commands',
    'greet with a jump',
    'roam in the woods',
    'nuzzle for attention',
    'paw for affection',
    'sniff around the garden',
    'greet with a wiggle',
    'play with squeaky toys',
    'pounce on toys',
    'guard the family',
    'herd children',
    'greet with a tail wag',
    'investigate new smells',
    'practice agility',
    'run zoomies',
    'guard the property',
    'search for hidden toys',
    'greet with a bark and a spin',
    'show off new tricks',
    'chase shadows',
  ];

  DogActivityGenerator() : super(_activities);
}
