import '../../../../generators/base/list_item_generator.dart';

/// A class that generates specialties of an artisans guild
class ArtisansSpecialtyGenerator extends ListItemGenerator<String> {
  static const _specialties = [
    'crafting and designing exquisite jewelry and accessories',
    'restoring ancient artifacts and relics',
    'offering legal counsel and representation for trade disputes',
    'providing top-notch financial analysis and advice',
    'offering skilled and efficient courier services',
    'expertise in the art of diplomacy and negotiation',
    'providing high-quality translation services for traders of all languages',
    'expertise in the development and implementation of trade policies',
    'providing specialized training and education for aspiring traders',
    'offering comprehensive insurance policies for high-risk trade ventures',
    'providing expert navigation and guidance through treacherous trade routes',
    'specializing in the trade of rare and exotic animals',
    'offering unique and customized packaging and branding solutions for products',
    'expertise in the art of forgery and counterfeiting',
    'providing tailored market research and analysis services',
    'specializing in the trade of rare and exotic textiles and fabrics',
    'offering luxury transportation services for high-profile traders',
    'providing expert appraisal services for fine art and antiques',
    'offering custom tailoring and garment-making services for traders',
    'expertise in the art of espionage and covert operations',
    'providing specialized security solutions for high-value trade goods',
    'offering specialized training in combat and self-defense for traders',
    'expertise in the trade of rare and exotic plants and herbs',
    'offering specialized training in negotiation and conflict resolution',
    'providing top-notch marketing and advertising services for traders',
    'expertise in the art of divination and prophecy',
    'specializing in the trade of rare and exotic musical instruments',
    'offering specialized training in leadership and management for trade organizations',
    'providing top-quality hospitality and entertainment services for traders',
    'expertise in the art of siegecraft and fortification',
    'specializing in the trade of rare and exotic wines and spirits',
    'offering specialized training in logistics and supply chain management',
    'providing top-quality it and digital solutions for trade organizations',
    'expertise in the art of hunting and trapping rare and exotic animals',
    'specializing in the trade of rare and exotic metals and minerals',
    'offering specialized training in risk management for trade ventures',
    'providing top-quality environmental and sustainability consulting services for trade organizations',
    'expertise in the art of astrology and celestial navigation',
    'specializing in the trade of rare and exotic perfumes and fragrances',
    'offering specialized training in public speaking and presentation skills for traders',
    'providing top-quality event planning and coordination services for trade organizations',
    'expertise in the art of illusion and sleight of hand',
    'specializing in the trade of rare and exotic weaponry and armor',
    'offering specialized training in cultural sensitivity and awareness for traders',
    'providing top-quality research and development services for trade organizations',
    'expertise in the art of siege engines and war machines',
    'specializing in the trade of rare and exotic vehicles and mounts',
  ];

  ArtisansSpecialtyGenerator() : super(_specialties);
}
