import '../../../../generators/base/list_item_generator.dart';

/// A class that generates a gnomish personality quirk
class ShifterPersonalityQuirkGenerator extends ListItemGenerator<String> {
  static const _shifterQuirks = [
    'frequently interrupts conversations',
    'always carries a lucky charm',
    'obsessed with collecting rare feathers',
    'has an irrational fear of water',
    'talks to animals as if they can understand',
    'has a penchant for speaking in rhymes',
    'has an insatiable curiosity about other cultures',
    'frequently changes their hairstyle',
    'always wears mismatched socks',
    'has an uncanny ability to mimic voices',
    'has an extensive collection of masks',
    'constantly doodles in the margins of their books',
    'believes in the power of astrology',
    'has a knack for finding hidden treasures',
    'keeps a diary and writes in it religiously',
    'has an unusual affinity for insects',
    'practices unconventional meditation techniques',
    'has a fear of heights',
    'obsessed with deciphering ancient texts',
    'speaks in riddles',
    'has an irrational fear of spiders',
    'possesses an exceptional memory for faces',
    'has a fascination with time-travel',
    'has a secret talent for playing a musical instrument',
    'always carries a small vial of scented oil',
    'has a fondness for bizarre fashion choices',
    'whispers to themselves when deep in thought',
    'obsessed with collecting exotic teas',
    'has an unusual connection with owls',
    'believes in the power of crystals',
    'prone to spontaneous dancing in public',
    'has an uncanny sense of direction',
    'frequently loses track of time',
    'has a peculiar habit of talking to plants',
    'obsessed with solving crossword puzzles',
    'always carries a journal to document their dreams',
    'has an uncanny ability to imitate accents',
    'fascinated by ancient ruins and lost civilizations',
    'practices a unique form of martial arts',
    'has an uncanny knack for finding hidden passages',
    'keeps a collection of lucky coins',
    'always has a pen behind their ear',
    'possesses an encyclopedic knowledge of herbal remedies',
    'has an unusual affinity for foggy weather',
    'believes in the existence of mythical creatures',
    'is an avid stargazer and amateur astronomer',
    'has a peculiar habit of naming inanimate objects',
    'obsessed with collecting rare seashells',
    'prone to daydreaming in the middle of conversations',
    'has an uncanny ability to find four-leaf clovers',
    'has an extensive collection of antique keys'
  ];

  ShifterPersonalityQuirkGenerator() : super(_shifterQuirks);
}
