import '../../base/list_item_generator.dart';

/// A class that generates celebrators for holidays
class HolidayCelebratorGenerator extends ListItemGenerator<String> {
  static const _celebrators = [
    "all people",
    "all people",
    "all people",
    "all people",
    "all people",
    "all people",
    "all people",
    "all people",
    "all people",
    "all people",
    "all people",
    "all people",
    "all people",
    "all people",
    "the villagers",
    "the townspeople",
    "the nobles",
    "the farmers",
    "the merchants",
    "the royal family",
    "the nomads",
    "the artisans",
    "the hunters",
    "the warriors",
    "the sailors",
    "the cityfolk",
    "the priests",
    "the scholars",
    "the druids",
    "the miners",
    "the blacksmiths",
    "the children",
    "the elders",
    "the healers",
    "the fishermen",
    "the sailors and traders",
    "the soldiers",
    "the nomadic tribes",
    "the peasants",
    "the desert dwellers",
    "the mountain clans",
    "the forest tribes",
    "the coastal towns",
    "the wandering folk",
    "the craftsmen",
    "the weavers",
    "the woodworkers",
    "the herders",
    "the horse riders",
    "the kingdom’s court",
    "the pilgrims",
    "the mystics",
    "the riverfolk",
    "the islanders",
    "the cave-dwellers",
    "the mountain folk",
    "the hill clans",
    "the fisherfolk",
    "the temple guardians",
    "the festival-goers",
    "the monks",
    "the sages",
    "the rulers and their subjects",
    "the lowlanders",
    "the highlanders",
    "the city guards",
    "the apprentices",
    "the tradesmen",
    "the royal court",
    "the guardians of the land",
    "the towns and villages",
    "the scholars and philosophers",
    "the worshippers",
    "the mystics and sages",
    "the coastal tribes",
    "the forest dwellers",
    "the desert tribes",
    "the plainsfolk",
    "the traveling merchants",
    "the emissaries",
    "the scouts and rangers",
    "the harvesters",
    "the traders and travelers",
    "the city artisans",
    "the animal herders",
    "the shipbuilders",
    "the explorers",
    "the cave explorers",
    "the desert caravans",
    "the nomads of the north",
    "the pilgrims of the sacred sites",
    "the worshippers of the old gods",
    "the acolytes of the temples",
    "the fisher clans",
    "the mountain rangers",
    "the traders of the marketplace",
    "the horse breeders",
    "the herbalists",
    "the wandering mystics",
    "the storytellers",
    "the farmers and their families",
    "the border towns",
    "the nomadic horsemen",
    "the tribes of the steppes",
    "the sun worshippers",
    "the moon worshippers",
    "the spirit guardians",
    "the descendants of the ancient kings",
    "the keepers of the old ways",
    "the dancers of the night",
    "the watchers of the stars",
    "the protectors of the sacred groves",
    "the wanderers of the wildlands",
    "the singers of the dawn",
    "the kingdom’s common folk",
    "the village councils"
  ];

  HolidayCelebratorGenerator() : super(_celebrators);
}
