import '../../../../generators/base/list_item_generator.dart';

/// A class that generates personalities adjectives for imps
class ImpPersonalityAdjectiveGenerator extends ListItemGenerator<String> {
  static const _adjectives = [
    'mischievous',
    'devious',
    'sly',
    'cunning',
    'crafty',
    'scheming',
    'manipulative',
    'conniving',
    'tricky',
    'diabolical',
    'wily',
    'wicked',
    'impish',
    'playful',
    'naughty',
    'clever',
    'resourceful',
    'fiendish',
    'sinister',
    'malicious',
    'nefarious',
    'sneaky',
    'deceitful',
    'sardonic',
    'sarcastic',
    'malevolent',
    'insidious',
    'vicious',
    'devilish',
    'treacherous',
    'cynical',
    'impulsive',
    'reckless',
    'adventurous',
    'bold',
    'audacious',
    'brash',
    'spirited',
    'feisty',
    'daring',
    'fearless',
    'plucky',
    'intrepid',
    'restless',
    'curious',
    'inquisitive',
    'insatiable',
  ];

  ImpPersonalityAdjectiveGenerator() : super(_adjectives);
}
