import '../../../../generators/base/list_item_generator.dart';

/// A class that generates activities that imps often do
class ImpActivityGenerator extends ListItemGenerator<String> {
  static const _activities = [
    'confuse adventurers',
    'spread fear among villagers',
    'sabotage plans',
    'disguise themselves to play tricks',
    'lurk in dark corners',
    'eavesdrop on conversations',
    'stealthily observe adventurers',
    'steal shiny objects',
    'spread superstition and fear',
    'cast curses',
    'haunt abandoned ruins',
    'toy with alchemical potions',
    'scare off rival creatures',
    'spread rumors',
    'cause trouble',
    'cause unrest in peaceful communities',
    'steal from treasure hunters',
    'cause chaos during celebrations',
    'sow nightmares in sleeping townsfolk',
    'disturb magical rituals',
    'play cruel jokes on hunters',
    'create illusions to lure prey',
    'trick travelers',
    'whisper dark secrets to the wicked',
    'play mind games',
    'whisper sinister thoughts',
    'create chaos in taverns',
    'lead wanderers into lost forests',
    'hide in shadows',
    'prank unsuspecting travelers',
    'trick or deceive magic-users',
    'play tricks on wizards',
    'steal valuable secrets',
    'tempt priests with sinful thoughts',
    'practice dark arts',
    'whisper eerie prophecies',
    'play cruel pranks on the righteous',
    'incite rebellion against rulers',
    'cast illusions',
    'plague wizards with bad luck',
    'disrupt royal ceremonies',
    'sneak into noble estates',
    'lead the unwary into danger',
    'mock others',
    'lead adventurers into cursed lands',
    'taunt enemies',
    'cause mischief',
    'disrupt magical experiments',
    'torture captured enemies',
    'steal magical components',
    'steal holy relics',
    'lead explorers into traps',
    'challenge wizards to magical duels',
    'whisper lies and half-truths',
    'torment the unsuspecting',
    'sow doubt among allies',
    'taunt guards',
    'manipulate magical artifacts',
    'spook livestock and animals',
    'cast illusions to confuse foes',
    'deface sacred symbols',
    'mock pompous nobles',
    'plot schemes',
    'sow discord between friends',
    'tease animals',
    'cause mayhem in marketplaces',
    'play pranks',
    'play with fire',
    'sow seeds of discord',
    'spy on others',
    'confound scholars with false knowledge',
    'play mind games with travelers',
    'deceive the wise and learned',
    'manipulate situations',
  ];

  ImpActivityGenerator() : super(_activities);
}
