import '../../base/list_item_generator.dart';

/// A class that represents a kingdom trouble
class KingdomTroubleGenerator extends ListItemGenerator<String> {
  static const _troubles = [
    'failed crops and famine',
    'disease outbreak',
    'resource depletion',
    'political unrest and rebellion',
    'religious conflict',
    'economic collapse',
    'invasion from a foreign power',
    'hostile neighboring kingdoms',
    'assassination attempts on the monarch',
    'sabotage of key infrastructure',
    'assassination of key officials',
    'mismanagement of resources',
    'banditry and lawlessness',
    'slavery and forced labor',
    'diplomatic crisis with allies',
    'drought and water shortages',
    'inflation and currency devaluation',
    'failure to maintain military readiness',
    'looming war with another kingdom',
    'failed diplomatic negotiations',
    'corruption within the government',
    'a catastrophic accident',
    'an environmental disaster',
    'rampant crime and organized crime syndicates',
    'invasions of dangerous creatures or monsters',
    'a powerful cult or religious sect causing unrest',
    'sabotage of critical trade routes',
    'a royal heir is kidnapped or held for ransom',
    'rebellion by a noble family or group of nobles',
    'a neighboring kingdom annexes a valuable territory',
    'a plague outbreak among livestock',
    'a natural disaster causing massive destruction',
    'the sudden death of a monarch',
    'conflict with a powerful mage or magical entity',
    'theft of valuable treasures or artifacts',
    'corruption and influence of the criminal underworld on politics',
    'mutiny among the military',
    'a hostile political faction gains power',
    'assassination of key merchants or traders',
    'corruption within the church or religious establishment',
    'a natural resource runs dry or is exhausted',
    'a powerful demon or otherworldly entity emerges',
    'a mysterious illness or curse affects the population',
    'a prophecy of doom or catastrophe',
    'a catastrophic fire in a major city',
    'severe weather and natural disasters',
    'civil war among rival factions',
    'a major technological disaster',
    'collapse of key trade agreements or treaties',
    'a new religious sect gains widespread influence and threatens the current power structure',
  ];

  KingdomTroubleGenerator() : super(_troubles);
}
