import '../../../../generators/base/list_item_generator.dart';

/// A class that generates forest encounters
class ForestEncounterGenerator extends ListItemGenerator<String> {
  static const _encounters = [
    'bandits',
    'banshees',
    'faerie dragons',
    'goblins',
    'lizardfolks',
    'pseudodragons',
    'satyrs',
    'gold dragons',
    'green dragons',
    'bugbears',
    'centaurs',
    'dryads',
    'green hags',
    'harpies',
    'hobgoblins',
    'orcs',
    'pixies',
    'sprites',
    'tribal warriors with mastiffs',
    'trolls',
    'woodcutters',
    'badgers',
    'brown bears',
    'giant elks',
    'giant owls',
    'giant poisonous snakes',
    'panthers',
    'treants',
    "will-o'-wisps",
    'awakened trees',
    'owls',
    'owlbears',
    'black bears',
    'boars',
    'dire wolves',
    'giant apes',
    'giant badgers',
    'giant bats',
    'giant boars',
    'giant frogs',
    'giant lizards',
    'giant spiders',
    'giant toads',
    'giant wasps',
    'unicorns',
    'wolves',
  ];

  ForestEncounterGenerator() : super(_encounters);
}
