import '../../../../generators/base/list_item_generator.dart';

/// A class that generates skills of cats
class CatSkillGenerator extends ListItemGenerator<String> {
  static const _skills = [
    'hunting skills',
    'illusion breaking',
    'helping with alchemy',
    'guarding',
    'silent movement',
    'teamwork',
    'finding shelter',
    'surveillance',
    'navigation',
    'camouflage',
    'sharp senses',
    'stalking',
    'tracking',
    'reconnaissance',
    'pouncing techniques',
    'feline communication',
    'survival instincts',
    'defense',
    'communication',
    'tracking skills',
    'stealth',
    'anticipation',
    'invisibility',
    'ghost whispering',
    'combat readiness',
    'perception',
    'survival skills',
    'hunting strategy',
    'acrobatics',
    'scent tracking',
    'setting traps',
    'emotional healing',
    'helping with potion brewing',
    'scouting',
    'scavenging',
    'combat maneuvers',
    'climbing',
    'first aid',
    'communication skills',
    'resource gathering',
    'empathy',
    'telepathy',
    'adapting to environment',
    'fishing',
    'protective instincts',
    'escape tactics',
    'hiding',
    'spiritual guidance',
    'distracting enemies',
    'ambushing',
    'enchanted artifact detection',
    'alertness',
    'teleportation',
    'intelligence',
    'surviving in various climates',
    'quick reflexes',
    'fortune telling',
    'dream manipulation',
    'ferocity',
    'stamina',
    'territory marking',
    'helping with herbology',
    'enchantment',
    'ambush tactics',
    'finding resources',
    'tracking scents',
    'aura sensing',
    'hunting',
    'levitation',
    'patrolling',
    'cooperation',
    'helping with spellcasting',
    'agility',
    'magic sensing',
    'night vision',
    'phasing',
    'tracking prey',
    'charm',
    'intuition',
    'protection',
    'sneaking',
    'enchanted music',
    'shapeshifting',
    'intimidation',
    'trapping',
    'spell countering',
    'dexterity',
    'patience',
    'observation',
  ];

  CatSkillGenerator() : super(_skills);
}
