import '../../../../generators/base/list_item_generator.dart';

/// A class that generates activities that birds often do
class BirdActivityGenerator extends ListItemGenerator<String> {
  static const _activities = [
    'capture',
    'mate',
    'screech',
    'roost',
    'fly',
    'peck',
    'strut confidently to display dominance',
    'hover',
    'carry small objects to build nests',
    'sing enchanting melodies',
    'scavenge for resources',
    'hunt',
    'communicate',
    'migrate',
    'flock',
    'flap',
    'hunt for elusive prey',
    'perform mesmerizing mating dances',
    'guard',
    'play',
    'swirl gracefully in aerial displays',
    'nuzzle affectionately',
    'call out to their companions',
    'swoop',
    'build intricate nests',
    'interact with other creatures',
    'snuggle closely with their companions',
    'dive',
    'embark on epic migratory journeys',
    'gracefully fly through the sky',
    'flock together in large groups',
    'groom',
    'watch',
    'watch over their territory with vigilance',
    'blend into the surroundings with camouflage',
    'soar',
    'chirp joyfully to communicate',
    'glide',
    'curiously explore their surroundings',
    'dance',
    'explore new territories with curiosity',
    'hover in mid-air to inspect their surroundings',
    'soar high above the clouds',
    'swirl',
    'scavenge',
    'meticulously groom their feathers',
    'nest',
    'snuggle',
    'sing',
  ];

  BirdActivityGenerator() : super(_activities);
}
