import '../../../../generators/base/list_item_generator.dart';

/// A class that generates breeks of cats
class CatBreedGenerator extends ListItemGenerator<String> {
  static const _breeds = [
    'bombay',
    'manx',
    'highlander',
    'turkish angora',
    'bambino',
    'persian',
    'devon rex',
    'american curl',
    'nebelung',
    'ragdoll',
    'cornish rex',
    'lynx',
    'ocelot',
    'bengal',
    'savannah',
    'jaguarundi',
    'tonkinese',
    'munchkin',
    'norwegian forest',
    'british shorthair',
    'siamese',
    'donskoy',
    'kurilian bobtail',
    'ragamuffin',
    'bobcat',
    'ocicat',
    'thai',
    'oriental',
    'napoleon',
    'egyptian mau',
    'chausie',
    'caracal',
    'american shorthair',
    'selkirk rex',
    'sokoke',
    'himalayan',
    'japanese bobtail',
    'siberian',
    'lykoi',
    'singapura',
    'tabby',
    'peterbald',
    'burmese',
    'chartreux',
    'khao manee',
    'pixie-bob',
    'turkish van',
    'sphynx',
    'havana brown',
    'scottish fold',
    'snowshoe',
    'ragamese',
    'laperm',
    'russian blue',
    'minskin',
    'maine coon',
    'somali',
    'toyger',
    'cymric',
    'birman',
    'serval',
    'abyssinian',
    'serval',
    'wildcat',
    'leopard cat',
    'sand cat',
    'margay',
    'pallesa\'s'
  ];

  CatBreedGenerator() : super(_breeds);
}
