import '../../../../enums/race.dart';

const genericPersonalityTraits = [
  'acts on impulse',
  'has an even temper',
  'would rather act than talk or think',
  'will ponder the pros and cons before making a decision',
  'gets bored easily',
  'has a highly variable mood',
  'is bipolar',
  'is always serene',
  'is very patient',
  'is very impatient',
  'rarely thinks ahead',
  'is always very calm',
  'is always prepared',
  'is always very excited',
  'always has a backup plan',
  'is very focused',
  'is very cynical',
  'is an hopeless romantic',
  'uses sarcasm and insults commonly',
  'always goes straight to the point',
  'is very direct',
  'always keeps score',
  'is very competitive',
  'changes subjects very often',
  'is always ironic',
  'is very selfish',
  'will always prioritize the needs of other people',
  'shows very little empathy towards others',
  'is very empathic towards others',
  'is always ready to help others',
  'is polite and respectful',
  'is a pacifist',
  'is kind and generous',
  'easily holds grudges',
  'is very benevolent',
  'is quick to forgive',
  'is prone to violence',
  'is a very good diplomat and always works towards resolution of conflict',
  'is very good at defusing tensions',
  'often spies on other people',
  'always plays fair',
  'hates fair play',
  'is very quick to trust other people',
  'is very slow to trust other people',
  'is very obstinate',
  'is not very obstinate',
  'is very optimistic',
  'is very pessimistic',
  'is an example of modesty',
  'is very self-confident',
  'has no self-confidence',
  'rarely speaks',
  'is very talkative',
  'only talks in whispers',
  'only talks loudly',
  'is very generous',
  'is very greedy',
  'is materialistic',
  'is non-materialistic',
  'is very cowardly',
  'is very courageous, to a fault',
  "doesn't care about risks or odds.",
  'judges people by their actions, not their words',
  'takes everything at face-value',
  'constantly looks for the loophole',
  'is a perfectionist',
  "can't stand laziness.",
  "can't keep a secret.",
  'is very good at keeping secrets'
];

const Map<List<Race>, List<String>> personalityTraitsMap = {};
