import '../../base/list_item_generator.dart';

/// A class that generates dates for holidays
class HolidayDateGenerator extends ListItemGenerator<String> {
  static const _dates = [
    'the appearance of the first star',
    'the arrival of spring rains',
    'the arrival of the cold winds',
    'the arrival of the comet',
    'the arrival of the first birds of spring',
    'the arrival of the first frost',
    'the arrival of the first snow',
    'the arrival of the frost',
    'the arrival of the harvest moon',
    'the arrival of the migratory animals',
    'the arrival of the monsoon',
    'the arrival of the new year',
    'the arrival of the spring rains',
    'the autumn equinox',
    'the beginning of spring',
    'the beginning of the fishing season',
    'the beginning of the harvest festival',
    'the beginning of the long summer',
    'the beginning of the moon festival',
    'the beginning of the new year',
    'the beginning of the planting season',
    'the beginning of the rainy season',
    'the beginning of the winter feast',
    'the beginning of the winter solstice',
    'the blooming of the sacred flower',
    'the blooming of the sacred tree',
    'the blossoming of the sacred grove',
    'the breaking of dawn',
    'the breaking of the clouds',
    'the breaking of the drought',
    'the breaking of the ice',
    'the coming of the great storm',
    'the cooling of the air',
    'the cooling of the earth',
    'the cresting of the great river',
    'the dark moon',
    'the dawn of the longest day',
    'the end of autumn',
    'the end of the dry season',
    'the end of the festival season',
    'the end of the fishing season',
    'the end of the gathering storm',
    'the end of the growing season',
    'the end of the harvest',
    'the end of the hunting season',
    'the end of the ice melt',
    'the end of the long night',
    'the end of the rainy season',
    'the end of the school year',
    'the end of the wet season',
    'the end of winter',
    'the final gathering of the harvest',
    'the final hour before dawn',
    'the final night of the year',
    'the final week of summer',
    'the first bloom of spring',
    'the first bloom of the flowers',
    'the first break of the summer heat',
    'the first breath of the new season',
    'the first breath of winter',
    'the first chilly night of autumn',
    'the first cold snap of winter',
    'the first cool breeze of fall',
    'the first crack of thunder',
    'the first day of autumn',
    'the first day of summer',
    'the first day of the festival season',
    'the first day of the great migration',
    'the first day of the harvest',
    'the first day of the holiday season',
    'the first day of the market festival',
    'the first day of the rainy season',
    'the first day of the school year',
    'the first day of winter',
    'the first evening of autumn',
    'the first evening star',
    'the first flight of the butterflies',
    'the first frost',
    'the first frost of autumn',
    'the first frost of the year',
    'the first fruit of the season',
    'the first full moon of spring',
    'the first full moon of winter',
    'the first gathering of the harvest',
    'the first heat of summer',
    'the first light of dawn',
    'the first light of the summer solstice',
    'the first mist of autumn',
    'the first morning dew',
    'the first new moon of the year',
    'the first night of frost',
    'the first night of the summer festival',
    'the first night of the winter festival',
    'the first rain',
    'the first rain of autumn',
    'the first rain of summer',
    'the first scent of spring',
    'the first sign of winter',
    'the first snowfall',
    'the first snowfall of winter',
    'the first snowmelt',
    'the first sound of thunder',
    'the first star of the summer night',
    'the first sunrise of summer',
    'the first thunderstorm',
    'the first thunderstorm of spring',
    'the first thunderstorm of the year',
    'the first warm breeze',
    'the first warm day of spring',
    'the first week of autumn',
    'the first week of spring',
    'the first week of summer vacation',
    'the first week of the harvest festival',
    'the first week of the new year',
    'the first whisper of wind',
    'the first whisper of winter winds',
    'the full bloom of the trees',
    'the full moon',
    'the gathering of the clouds',
    'the gathering of the four winds',
    'the gathering of the stars',
    'the height of summer',
    'the height of the harvest',
    'the height of the monsoon season',
    'the height of the rainy season',
    'the height of the spring planting',
    'the height of the winds',
    'the height of the winter winds',
    'the high tide',
    'the last breath of autumn',
    'the last day of autumn',
    'the last day of the harvest',
    'the last day of the rainy season',
    'the last day of the winter feast',
    'the last day of winter',
    'the last evening of autumn',
    'the last full moon of summer',
    'the last full moon of winter',
    'the last harvest',
    "the last leaf's fall",
    'the last night before winter',
    'the last night of summer',
    'the last night of the full moon',
    'the last night of the twin moons',
    'the last rain of the wet season',
    'the last week of summer',
    'the longest day of the year',
    'the longest night of the year',
    'the low tide of the great river',
    'the mid-point of summer',
    'the mid-summer festival',
    'the middle of autumn',
    'the middle of the harvest',
    'the middle of the rainy season',
    'the middle of the summer festival',
    'the midnight of the new year',
    'the new moon',
    'the return of the migratory birds',
    'the return of the phoenix',
    'the return of the sun',
    'the rising of the harvest sun',
    'the rising of the northern star',
    'the rising of the third moon',
    'the rising of the twin moons',
    'the setting of the great sun',
    'the setting of the twin suns',
    'the shortest day of the year',
    'the sighting of the first swan',
    'the solstice',
    'the start of the autumn equinox',
    'the start of the dry season',
    'the start of the first frost',
    'the start of the harvest',
    'the start of the school term',
    'the start of the spring planting',
    'the start of the summer holidays',
    'the start of the summer solstice',
    'the start of the winter winds',
    'the summer solstice',
    'the time of the eclipse',
    'the time of the falling stars',
    'the time of the great migration',
    'the time of the northern lights',
    'the time of the starfall',
    'the time of the twin sunsets',
    'the time of the waning moon',
    'the turning of the great wheel',
    'the turning of the leaves',
    'the turning of the season',
    'the turning of the year',
    'the waxing moon'
  ];

  HolidayDateGenerator() : super(_dates);
}
