import '../../../../generators/base/list_item_generator.dart';

/// A class that generates quirks of imps
class ImpQuirkGenerator extends ListItemGenerator<String> {
  static const _quirks = [
    'obsessively counting objects',
    'constantly sharpening their claws',
    'fidgeting with small trinkets',
    'collecting shiny baubles',
    'speaking in rhymes',
    'developing peculiar tastes in food',
    'insisting on sleeping in unusual places',
    'playing practical jokes on their allies',
    'imitating the voices of others',
    'becoming easily distracted by illusions',
    'hoarding peculiar items',
    'dancing erratically when excited',
    'performing odd rituals for good luck',
    'craving spicy or sour foods',
    'harboring an unusual fear of water',
    'obsessively grooming their wings',
    'talking to themselves in whispers',
    'rearranging objects in strange patterns',
    'chanting mysterious incantations',
    'collecting odd smells in vials',
    'forming peculiar alliances with creatures',
    'speaking in cryptic riddles',
    'fixating on rare or exotic materials',
    'enjoying mischief for mischief\'s sake',
    'fascinated by illusions and trickery',
    'developing an insatiable curiosity',
    'possessing an unusual affinity for shadows',
    'delighting in the misfortune of others',
    'craving attention from powerful beings',
    'displaying unpredictable mood swings',
    'tinkering with arcane devices',
    'being overly protective of their possessions',
    'having a penchant for dark humor',
    'exhibiting an uncanny sense of timing',
    'being strangely drawn to forbidden knowledge',
    'possessing a hidden talent for mimicry',
    'becoming fixated on particular individuals',
    'seeking out unusual experiences',
    'becoming overly attached to their companions',
    'developing an affinity for ancient artifacts',
    'displaying an unusual fondness for fire',
    'acting as if they know more than they reveal',
    'exhibiting an odd fascination with insects',
    'having a tendency to vanish without a trace',
    'acting as if they have a secret agenda',
    'developing peculiar superstitions',
    'displaying an unusual bravery in dangerous situations',
    'showing a keen interest in magical phenomena',
    'being drawn to areas of high magical energy',
    'becoming skilled at picking locks',
    'showing a knack for finding hidden treasures',
    'exhibiting a strange fondness for darkness',
    'displaying an uncanny ability to avoid danger',
    'possessing a remarkable memory for details',
    'acting as if they can see things others can\'t',
    'showing an unusual loyalty to their companions',
    'exhibiting a surprising level of intelligence',
    'having a habit of speaking in whispers',
    'developing a taste for exotic cuisine',
    'displaying an uncanny ability to predict events',
    'exhibiting an odd sense of humor',
    'possessing a knack for solving puzzles',
    'showing a remarkable resilience to harm',
    'developing a habit of collecting strange souvenirs',
    'acting as if they know secret knowledge',
    'showing an uncanny ability to sense danger',
    'exhibiting a surprising skill at disguise',
    'having a tendency to disappear for long periods',
    'displaying a fascination with illusions',
    'showing an uncanny ability to understand languages',
    'exhibiting a talent for mimicry',
    'developing a habit of pulling harmless pranks',
    'acting as if they can manipulate luck',
    'showing a surprising talent for singing',
    'exhibiting an unusual fondness for music',
    'having a knack for finding hidden paths',
    'displaying an uncanny intuition for danger',
    'possessing a keen sense of smell',
    'acting as if they can communicate with animals',
    'showing a remarkable skill at stealth',
    'exhibiting a surprising talent for navigation',
    'having a habit of collecting strange artifacts',
    'displaying an unusual tolerance for pain',
    'showing a remarkable ability to adapt to new situations',
    'exhibiting a talent for illusion magic',
    'having a knack for escaping from tight spots',
    'displaying an uncanny ability to find shortcuts',
    'showing a surprising talent for storytelling',
    'exhibiting a keen sense of curiosity',
    'possessing a knack for finding hidden knowledge',
    'acting as if they can sense emotions',
    'showing a remarkable resilience to magic',
    'exhibiting an unusual fondness for puzzles',
    'having a habit of disappearing when bored',
    'displaying an uncanny ability to sense danger',
    'showing a surprising skill at negotiation',
    'exhibiting a knack for predicting the future',
    'possessing an uncanny ability to avoid traps',
    'acting as if they can control the weather',
    'showing a remarkable talent for mimicry',
    'exhibiting an unusual fondness for shiny objects',
    'having a knack for finding hidden passages',
    'displaying a surprising aptitude for disguise',
    'showing an uncanny ability to avoid capture',
    'exhibiting a talent for stealth',
    'possessing a knack for finding lost items',
    'acting as if they can see in the dark',
    'showing a remarkable talent for navigation',
    'exhibiting an unusual fondness for riddles',
    'having a habit of speaking in cryptic phrases',
  ];

  ImpQuirkGenerator() : super(_quirks);
}
