const smithyGoods = {
  'halberd': '20 gp',
  'net': '1 gp',
  'blowgun': '10 gp',
  'light hammer': '2 gp',
  'dart': '5 cp',
  'heavy crossbow': '50 gp',
  'half plate medium armor': '750 gp',
  'smoldering armor light medium or heavy armor': '75 gp',
  'scimitar': '25 gp',
  'club': '1 sp',
  'breastplate medium armor': '400 gp',
  'studded leather light armor': '45 gp',
  'javelin': '5 sp',
  'greatclub': '2 sp',
  'padded light armor': '5 gp',
  'quarterstaff': '2 sp',
  'sickle': '1 gp',
  'dagger': '2 gp',
  'battleaxe': '10 gp',
  'cast-off armor light medium or heavy armor': '50 gp',
  'mace': '5 gp',
  'hide medium armor': '10 gp',
  'sling': '1 sp',
  'lance': '10 gp',
  'chain shirt medium armor': '50 gp',
  'rapier': '25 gp',
  'shortsword': '10 gp',
  'longsword': '15 gp',
  'arrows': '1 gp',
  'war pick': '5 gp',
  'plate heavy armor': '1500 gp',
  'greataxe': '30 gp',
  'light crossbow': '25 gp',
  'padded': '5 gp',
  'maul': '10 gp',
  'shield': '10 gp',
  'leather': '10 gp',
  'ring mail heavy armor': '30 gp',
  'splint heavy armor': '200 gp',
  'whip': '2 gp',
  'chain mail heavy armor': '75 gp',
  'bullets': '4 cp',
  'glaive': '20 gp',
  'handaxe': '5 gp',
  'armor of gleaming medium or heavy armor': '75 gp',
  'leather light armor': '10 gp',
  'pike': '5 gp',
  'morningstar': '15 gp',
  'trident': '5 gp',
  'warhammer': '15 gp',
  'shortbow': '25 gp',
  'greatsword': '50 gp',
  'shield of expression': '50 gp',
  'scale mail medium armor': '50 gp',
  'bolts': '1 gp',
  'needles': '1 gp',
  'spear': '1 gp',
  'hand crossbow': '75 gp',
  'flail': '10 gp',
  'longbow': '50 gp'
};
