import '../../../../generators/base/list_item_generator.dart';

/// A class that generates quests for artisans guild
class ArtisansQuestGenerator extends ListItemGenerator<String> {
  static const _quests = [
    'craft a beautiful and intricate piece of jewelry for a high-profile client within a tight deadline',
    'transport a fragile and valuable piece of artwork across dangerous terrain without damaging it',
    'help a struggling member of the guild get back on their feet by providing training and resources',
    "investigate a series of mysterious accidents and mishaps that have been occurring in the guild's workshops",
    'negotiate a fair price for a rare and exotic material that a wealthy buyer is desperate to acquire',
    "set up a temporary shop in a new city or region to test the market and expand the guild's reach",
    'create a unique and innovative design for a new product that can set the guild apart from its competitors',
    'retrieve a stolen guild artifact from a dangerous criminal gang and bring the perpetrators to justice',
    "organize a fundraiser or charity event to raise money for a good cause and improve the guild's public image",
    'acquire a rare and powerful magical component for a high-paying customer who wants to use it for a spell',
    'investigate and root out a group of counterfeiters who have been producing fake guild products',
    'deliver a highly sensitive and confidential package to a trusted client without letting it fall into the wrong hands',
    'help a member of the guild expand their business by providing them with a loan or investment',
    'recover a lost shipment of goods from a treacherous and unforgiving wilderness',
    "organize a tour of the guild's workshops and factories to promote transparency and build trust with customers",
    'acquire a highly sought-after apprenticeship with a master craftsman for a promising young talent in the guild',
    'investigate a dangerous new competitor who has been using unethical and possibly illegal methods to gain an advantage',
    'help a wealthy noble family plan and execute a lavish and impressive wedding or banquet',
    "retrieve a stolen or lost magical artifact that is essential for the guild's operations",
    'create a special and unique gift for a beloved and respected member of the community who has done a great service to the guild',
    "organize a large-scale public event or festival to showcase the guild's products and attract new customers",
    "acquire a rare and expensive piece of equipment that can improve the efficiency and quality of the guild's work",
    "investigate a series of mysterious illnesses and accidents that have been plaguing the guild's workers",
    'set up a new and innovative training program to help members of the guild improve their skills and knowledge',
    'retrieve a rare and valuable book or manuscript from a dangerous and forbidden place',
    'negotiate a truce or peace agreement with a rival guild to avoid open conflict and preserve the interests of both sides',
    'help a member of the guild expand their business into a new and potentially lucrative market',
    'deliver a powerful and important speech at a high-stakes meeting or negotiation to sway opinions and gain support',
    'acquire a rare and valuable animal or creature that can be used as a source of materials or inspiration',
    "investigate and root out a corrupt official or bureaucrat who is abusing their power and harming the guild's interests",
    'create a special and unique design for a member of a royal family or other high-ranking dignitary',
    'retrieve a valuable and treasured family heirloom from a distant and dangerous land',
    'help a member of the guild recover from a personal crisis or setback and regain their confidence and motivation',
    'establish a new partnership or alliance with a powerful and influential organization or institution',
    'acquire a rare and exotic spice or ingredient that can be used to create unique and delicious dishes',
    'design and build a grand monument or sculpture to honor a powerful patron or leader',
    "investigate a string of mysterious and unexplained accidents or disasters that have been plaguing the guild's operations",
    'provide security and protection for a large-scale public event or festival',
    'recover a stolen or lost artifact that is of great historical or cultural significance',
    "establish a new training program for aspiring artisans to expand the guild's influence and reach",
    'set up a covert operation to gather information on a powerful and secretive rival guild',
    "acquire a rare and exotic animal or creature for use in the guild's productions or exhibitions",
    'assist a group of refugees or displaced people in setting up a new community or settlement',
    'negotiate a treaty or alliance with a neighboring kingdom or faction to secure trade and protection',
    'investigate rumors of a powerful and dangerous magical artifact that is being sought after by numerous factions',
    'help a group of struggling artisans in a nearby town or village improve their skills and businesses',
    'establish a new department or division within the guild to focus on the creation of magical items and artifacts',
    'assist in the reconstruction of a city or town that has been devastated by war or disaster',
    "infiltrate a rival guild's headquarters or stronghold to gather information or steal valuable resources",
    'help a group of farmers or craftsmen in a nearby region form their own guild and establish themselves in the market'
  ];

  ArtisansQuestGenerator() : super(_quests);
}
