import '../../../../generators/base/list_item_generator.dart';

/// A class that generates skills of monkeys
class MonkeySkillGenerator extends ListItemGenerator<String> {
  static const _skills = [
    'climbing',
    'swinging through trees',
    'mimicking sounds',
    'throwing objects with precision',
    'stealing unnoticed',
    'finding hidden food',
    'scouting from high vantage points',
    'balancing on thin surfaces',
    'making tools from natural objects',
    'coordinating group distractions',
    'opening locks or containers',
    'dodging attacks swiftly',
    'communicating with gestures',
    'leading companions through dense jungles',
    'sensing danger from above',
    'ambushing with surprise attacks',
    'escaping from traps',
    'hiding in plain sight',
    'navigating complex mazes',
    'leaping across wide gaps',
    'creating diversions with noises',
    'detecting enemy movements',
    'grabbing objects mid-air',
    'using vines for quick movement',
    'escaping from confined spaces',
    'disabling simple traps',
    'distracting foes with gestures',
    'retrieving items from dangerous places',
    'locating hidden pathways',
    'sensing changes in weather',
    'breaking into locked areas',
    'coordinating group ambushes',
    'eavesdropping without being seen',
    'mimicking voices',
    'swinging between trees effortlessly',
    'carrying messages across long distances',
    'detecting edible plants',
    'leading groups through dangerous terrain',
    'locating hidden caves or shelters',
    'disarming rudimentary traps',
    'using natural resources for defense',
    'avoiding predators',
    'creating improvised tools',
    'detecting hidden dangers',
    'foraging in hard-to-reach places',
    'communicating across long distances',
    'organizing small groups for tasks',
    'using surroundings to blend in',
    'climbing walls or steep cliffs',
    'solving complex puzzles',
    'observing enemy movements from a distance',
    'leading searches for lost companions',
    'using objects to distract enemies',
    'forging paths through dense forests',
    'spying on enemy camps unnoticed',
    'detecting hidden traps or snares',
    'guiding others through difficult terrain',
    'outsmarting more powerful enemies',
    'using body language to signal warnings',
    'teaching others new skills',
    'manipulating tools with dexterity',
    'decoding simple symbols or markings',
  ];

  MonkeySkillGenerator() : super(_skills);
}
