import '../../../../generators/base/list_item_generator.dart';

/// A class that generates ocean features
class OceanFeatureGenerator extends ListItemGenerator<String> {
  static const _features = [
    'has a treacherous reef that poses a danger to ships',
    'is home to a colony of seals that bask on the shore',
    'has a stretch of coastline dotted with sea caves',
    'has a natural whirlpool that can pull ships under',
    'is home to a species of plankton that create a beautiful display at night',
    'has a section of coastline with towering sea stacks',
    'is a popular spot for migrating whales to pass through',
    'has a beach littered with colorful shells and sea glass',
    'has an underwater graveyard of shipwrecks and debris',
    'has a deep underwater canyon that is home to unique species of fish and sea creatures',
    'has a section where the water is so calm and clear that the ocean floor can be seen from the surface',
    'is a breeding ground for sea turtles',
    'has a section where the water is filled with dangerous jellyfish',
    'has a section where hot and cold currents converge, creating a unique ecosystem',
    'has a natural arch or bridge made of rock that extends out into the water',
    'is surrounded by lush greenery and forests that grow right up to the shoreline',
    'has a section where the water is a vibrant shade of turquoise or green',
    'has a strong tide that changes direction with the phases of the moon',
    'is home to massive underwater volcanoes that emit steam and ash',
    'has a section that is constantly shrouded in thick fog',
    'is home to a school of intelligent dolphins that are rumored to communicate with humans',
    'has a sandy seabed that is dotted with ancient shipwrecks',
    'is surrounded by a dense thicket of seaweed and kelp',
    'has a section that is completely devoid of life, the dead zone',
    'has a surface that is covered in rainbow-colored oil slicks',
    'is home to a giant squid that terrorizes passing ships',
    'has a section with a massive coral reef that is teeming with life',
    'is surrounded by jagged rocks that create treacherous waves and currents',
    'has a section with a giant underwater cave system filled with air pockets',
    'is home to a race of underwater giants who rarely interact with humans',
    'is home to a group of playful sea otters who love to interact with humans',
    'has a section with an underwater city that has been abandoned for centuries',
    'has a surface that is covered in strange, glowing algae',
    'is surrounded by a towering wall of icebergs',
    'has a section with underwater geysers that shoot hot water high into the air',
    'is home to a giant sea serpent that is worshipped as a deity by some cultures',
    'has a section with underwater caves that are home to schools of exotic fish',
    'has a surface that is covered in a thick layer of floating debris from a recent storm',
    'is home to a clan of rogue pirates who use the ocean as their base of operations',
    'is a sprawling archipelago with thousands of islands',
    'is a bustling port city with a large harbor',
  ];

  OceanFeatureGenerator() : super(_features);
}
