import '../../../../generators/base/list_item_generator.dart';

/// A class that generates body types of imps
class ImpPhysiqueGenerator extends ListItemGenerator<String> {
  static const _physique = [
    'lean',
    'gangly',
    'compact',
    'sinewy',
    'hunched',
    'stooped',
    'twisted',
    'lanky',
    'gnarled',
    'crooked',
    'skeletal',
    'slender',
    'bony',
    'stooped',
    'hunched',
    'scrawny',
    'emaciated',
    'spindly',
    'frail',
    'squat',
    'stubby',
    'stocky',
    'barrel-chested',
    'bulky',
    'burly',
    'solid',
    'muscular',
    'sinister',
    'compact',
    'lithe',
    'hunched',
    'stooped',
    'gnarled',
    'crooked',
    'hulking',
    'sturdy',
    'skeletal',
    'slender',
    'bony',
    'stooped',
    'hunched',
    'scrawny',
    'emaciated',
    'spindly',
    'frail',
    'squat',
    'stubby',
    'stocky',
    'barrel-chested',
    'bulky',
    'burly',
    'solid',
    'muscular',
    'sinister',
    'compact',
    'lithe',
    'hunched',
    'stooped',
    'gnarled',
    'crooked',
    'hulking',
    'sturdy',
  ];

  ImpPhysiqueGenerator() : super(_physique);
}
