import '../../../../generators/base/list_item_generator.dart';

/// A class that generates physical features of imps
class ImpFeatureGenerator extends ListItemGenerator<String> {
  static const _features = [
    'horns',
    'tail',
    'wings',
    'claws',
    'fangs',
    'sharp teeth',
    'spiked back',
    'pointed ears',
    'forked tongue',
    'warty skin',
    'glowing eyes',
    'bat-like wings',
    'tufted tail',
    'barbed tail',
    'sharp claws',
    'serrated teeth',
    'fangs',
    'spiny tail',
    'razor-sharp talons',
    'leathery wings',
    'long tail',
    'hunched back',
    'razor-sharp horns',
    'hairy body',
    'long, thin fingers',
    'webbed feet',
    'sickle-shaped claws',
    'snakeskin texture',
    'shaggy fur',
    'glowing runes on skin',
    'multiple eyes',
    'extra limbs',
    'cracked skin',
    'tattered wings',
    'glowing aura',
    'smoky tendrils',
    'tentacles',
    'bone protrusions',
    'shimmering scales',
    'curled horns',
    'gnarled talons',
    'bat-like ears',
    'slit pupils',
    'sharp spines',
    'chitinous exoskeleton',
    'forked tail',
    'razor-edged feathers',
    'tendrils',
    'furry tail',
    'skeletal wings',
    'glowing veins',
    'feline eyes',
    'beak',
    'feathers',
    'spider-like legs',
    'demonic runes',
    'glowing symbols',
    'whiskers',
    'clawed feet',
    'scorpion-like tail',
    'hunchback',
    'fanged maw',
    'spiked tail',
    'feathery wings',
    'crimson scales',
    'horned tail',
    'glowing orbs',
    'antennae',
    'ridged horns',
    'chitinous wings',
    'crimson eyes',
    'razor-sharp beak',
    'bulging eyes',
    'long tongue',
    'forked tongue',
    'serrated fins',
    'elongated limbs',
    'serpentine tail',
    'crimson talons',
    'bat-like features',
    'swirling patterns on skin',
    'glowing tendrils',
    'cat-like eyes',
    'dagger-like teeth',
    'scaled tail',
    'sickle-shaped horns',
    'retractable claws',
    'crimson fur',
    'bone spikes',
    'sharp beak',
    'elongated ears',
    'glowing fangs',
    'forked ears',
    'spiky tail',
    'lizard-like scales',
    'elongated snout',
    'feathered tail',
    'glowing tail',
    'bat-like nose',
    'clawed hands',
    'sharp spurs',
    'glowing runes on horns',
    'swirling patterns on wings',
    'glowing eyespots',
    'chitinous plating',
    'serrated claws',
    'torn wings',
    'glowing sigils',
    'crimson horns',
    'furry ears',
    'tentacle-like appendages',
    'cracked horns',
    'beetle-like carapace',
    'curled tail',
    'spiked tail',
    'glowing tufts of fur',
    'razor-sharp spines',
    'feathery crest',
    'glowing antennae',
    'glowing claws',
    'flaming tail',
    'glowing fur',
    'reptilian tail',
    'clawed wings',
    'hunchbacked posture',
    'spiked back',
    'serrated fins',
    'barbed appendages',
    'fiery mane',
    'shimmering feathers',
    'glowing stripes',
    'hairy legs',
    'chitinous limbs',
    'glowing carapace',
    'crimson feathers',
    'spiked crest',
    'razor-sharp spurs',
    'glossy scales',
    'razor-sharp beak',
    'glowing mane',
    'whip-like tail',
    'sinuous body',
    'sharp pincers',
    'swirling patterns on tail',
    'furry chest',
    'luminous eyes',
    'spiked mane',
    'bat-like wingspan',
    'sinewy tentacles',
    'hunched shoulders',
    'spiny carapace',
    'flaming eyes',
    'clawed feet',
    'spiked tail',
    'glowing claws',
    'razor-edged fins',
    'tattered wings',
    'chitinous shell',
    'feathery plumes',
    'twisted horns',
    'toxic spines',
    'crimson mane',
    'sharp talons',
    'crimson scales',
    'spiked fur',
    'sinister silhouette',
    'gnarled claws',
    'tendrils of darkness',
    'glowing talons',
    'serrated tail',
    'glowing tendrils',
    'sinewy tentacles',
    'hunched shoulders',
    'spiny carapace',
    'flaming eyes',
    'clawed feet',
    'spiked tail',
    'glowing claws',
    'razor-edged fins',
    'tattered wings',
    'chitinous shell',
    'feathery plumes',
    'twisted horns',
    'toxic spines',
    'crimson mane',
    'sharp talons',
    'crimson scales',
    'spiked fur',
    'sinister silhouette',
    'gnarled claws',
    'tendrils of darkness',
    'glowing talons',
    'serrated tail',
    'glowing tendrils',
  ];

  ImpFeatureGenerator() : super(_features);
}
